### ISSUE TITLE
i'm unable to load modules after accepting license agreement

### ISSUE THREAD

**Issue by eomwandho** [gltn/stdm#100]
After accepting license agreement I'm unable to load any modules. This happened when I clicked accept button, without checking the checkbox with information about reading the license.

**Comment by wondie** [comment]
Hi Eric, did the dialog show an error message that tells you should select the option "I agree the terms and conditions"?

**Comment by wondie** [comment]
Then that is expected. We want the user to check the checkbox "I agree..."

**Comment by eomwandho** [comment]
But if they forget, which in many case is expected. Then they should be
able to login and load the modules after marking the checkbox, before
accepting the terms.

In my case, even after marking the checkbox when the error showed and
clicking the accept button, I wasn't able to load the modules afterwards.

On Sat, Jul 2, 2016 at 10:38 AM, wondie <notifications@github.com> wrote:

> Then that is expected. We want the user to check the checkbox "I agree..."
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gltn/stdm/issues/100#issuecomment-230089160>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACkm99XXn3VKGYPVWyvY5JMGv5W8XqWJks5qRhWCgaJpZM4JDnQK>
> .
>



-- 


*Thanks and Regards,*
*Erick Opiyo*
*Cell: +254724590982*

**Comment by wondie** [comment]
Adding a check box validation is a common practice and it is like a signature.  

If the checkbox is checked, and the Accept button is clicked, it should load modules. In my side, it is working as expected. So I have to check it on your machine when we meet.

**Comment by eomwandho** [comment]
Try clicking the button before marking the checkbox. An error will pop up.
After mark the checkbox and again click the button. Exit QGIS and try log
in, do the modules appear?

My issue is that, if the user forgets to mark the button and does it
afterwards when the error appears. Then there is an issue with loading
modules after log in. Please try the above and tell me if you get the same
issue

On Sat, Jul 2, 2016 at 3:50 AM, wondie <notifications@github.com> wrote:

> Adding a check box validation is a common practice and it is like a
> signature.
>
> If the checkbox is checked, and the Accept button is clicked, it should
> load modules. In my side, it is working as expected. So I have to check it
> on your machine when we meet.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gltn/stdm/issues/100#issuecomment-230089543>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACkm95iMLcUgTG8OP1kn9jk3As-pPRA6ks5qRhhJgaJpZM4JDnQK>
> .
>



-- 


*Thanks and Regards,*
*Erick Opiyo*
*Cell: +254724590982*

**Comment by wondie** [comment]
I did what you said and the modules load. This is what I did. 
Clicked the Accepted button without checking the checkbox.
Then checked the checkbox, and clicked the accept button. All the modules load...
Then exited QGIS, and when I re-login, there is no license agreement module, as the registry flag is changed.

**Comment by eomwandho** [comment]
I wonder, why it's not working on my machine.

On Sat, Jul 2, 2016 at 4:12 AM, wondie <notifications@github.com> wrote:

> I did what you said and the modules load. This is what I did.
> Clicked the Accepted button without checking the checkbox.
> Then checked the checkbox, and clicked the accept button. All the modules
> load...
> Then exited QGIS, and when I re-login, there is no license agreement
> module, as the registry flag is changed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gltn/stdm/issues/100#issuecomment-230090262>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACkm9wGEFKSmvOpVBapqAo2a-la3TPtbks5qRh2HgaJpZM4JDnQK>
> .
>



-- 


*Thanks and Regards,*
*Erick Opiyo*
*Cell: +254724590982*

**Comment by wondie** [comment]
That is strange. Does the registry key showLicense change from 1 to 0 when you accept the license on stdm registry key?

**Comment by eomwandho** [comment]
On Linux QSettings the value is 0

On Sat, Jul 2, 2016 at 4:17 AM, wondie <notifications@github.com> wrote:

> That is strange. Does the registry key showLicense change from 1 to 0 when
> you accept the license on stdm registry key?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gltn/stdm/issues/100#issuecomment-230090421>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACkm92T7X94-jPCGTx6YjCzl57LEGxV6ks5qRh6ngaJpZM4JDnQK>
> .
>



-- 


*Thanks and Regards,*
*Erick Opiyo*
*Cell: +254724590982*

**Comment by wondie** [comment]
Maybe, my guess is it was unable to read the updated value. Could you add `print show_lic` on [this line.](https://github.com/gltn/stdm/blob/ref_config_mod/ui/license_agreement.py#L80)  and see what it prints on QGIS python console?

**Comment by wondie** [comment]
Hi Eric, 
This is strange. Which version of linux are you using? I want to test it from a virtual machine. 

In stdm registry, if you change showLicense to 1, the license agreement module pops up. If you change it to 0, it shouldn't show.

**Comment by eomwandho** [comment]
I'm using Ubuntu 16.04, when I change the value to one nothing shows.

On Sat, Jul 2, 2016 at 9:34 AM, wondie <notifications@github.com> wrote:

> Hi Eric,
> This is strange. Which version of linux are you using? I want to test it
> from a virtual machine.
>
> In stdm registry, if you change showLicense to 1, the license agreement
> module pops up. If you change it to 0, it shouldn't show.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gltn/stdm/issues/100#issuecomment-230101983>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACkm90p51MaIYXQKmv3og0aiMzBVqIxUks5qRmjwgaJpZM4JDnQK>
> .
>



-- 


*Thanks and Regards,*
*Erick Opiyo*
*Cell: +254724590982*

**Comment by wondie** [comment]
Ok I will test it and report back. When the value is 1 it should have shown license.

**Comment by eomwandho** [comment]
@wondie this is very strange

This is the value of ShowLicense
![ShowLicense value from QSettings (Linux and probably mac)](https://cloud.githubusercontent.com/assets/2696951/16541468/c084a064-4051-11e6-8143-622e71e2f4cf.png)

Printing ShowLicense from [show_lic](https://github.com/gltn/stdm/blob/ref_config_mod/ui/license_agreement.py#L95) Gives none

![screenshot from 2016-07-02 12-35-04](https://cloud.githubusercontent.com/assets/2696951/16541490/794f88e8-4052-11e6-9a57-40027e1af05e.png)


![screenshot from 2016-07-02 12-35-54](https://cloud.githubusercontent.com/assets/2696951/16541483/4dc3b816-4052-11e6-919d-f09c746ba48b.png)

**Comment by eomwandho** [comment]
I think the problem was that in systems like Linux and mac, values from the registry come in as 'unicode'.

![screenshot from 2016-07-02 13-12-53](https://cloud.githubusercontent.com/assets/2696951/16541724/00e6128a-4059-11e6-9861-c2c8affd5224.png)

So to help people with this type of system. You can look at how to take care of values that are not numbers

**Comment by eomwandho** [comment]
Adding the following helped
```

        if show_lic == 1 or show_lic == unicode(1):
            return True
        elif show_lic == 0 or show_lic == unicode(0):
            self.accepted = True
            return False
```

**Comment by wondie** [comment]
That is great find Eric. Thank you! We have to know be careful on registry integer values. I will incorporate the above code in my next commit.

**Comment by wondie** [comment]
The code you have suggested is incorporated in this [commit](https://github.com/gltn/stdm/commit/dac7b362c9ca4bb21a896c3f6b0f2a053934b0cc).
