### ISSUE TITLE
Configuration Wizard Does Not Create User Folder

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#112]
After removing the .stdm folder in the current user directory, I successfully re-ran the wizard but it did not create the folders as specified in the first page of the wizard i.e. 

- Supporting documents
- Documents output
- Documents template

Please incorporate logic for checking if these folders exist and create accordingly.

**Comment by pgathogo** [comment]
@gkahiu thanks for noting this, but from our earlier discussions we agreed that the wizard first checks if the path settings exists in the registry before resorting to the entries in .stdm folder. 
To test if this works correctly, try deleting(renaming) one of the registry keys e.g `NetDocumentResource`, then delete the `'document'` folder in the .stdm folder, see if the `'document'` folder will be created.

**Comment by gkahiu** [comment]
Hi Paul,

It works when the registry key does not exist but also the wizard should confirm that indeed whatever is specified in the registry key indeed does exist. An example of a use case is when a user decides to manually remove the .stdm folder; in such a scenario, the _NetDocumentResource_ will point to an existing location which, however, in reality does exists. Also, it is normally good practice (especially for folder and file paths) to assert that they exist and either recreate them or notify user. 

I would also suggest that you use PyQt for constructing file paths instead of Python so that there will be no need of formatting the slashes to conform to Windows or Linux.

**Comment by pgathogo** [comment]
Hello John,

Well said, let me review this.

**Comment by pgathogo** [comment]
Fixed.
Code for reading and creating of path settings is now much cleaner.
