### ISSUE TITLE
STDM Error Log Contains Non-STDM Errors

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#115]
The stdm_error_xxx.log file contains includes tracebacks that are not related to STDM and this is not ideal. The QgsMessageLog incorporates error messages from different plugins including STDM. I would suggest we disable it until a more applicable solution is available.

Thoughts?

**Comment by wondie** [comment]
That is noted. This might not be desirable but sometimes knowing any other plugin error might be useful, as it also includes QGIS errors itself. In case of an error, or if something is not working properly, the log can give us the full picture. Also, it will be disabled by default. However, if you think it is not desirable, I will remove it.

**Comment by gkahiu** [comment]
I do not agree on the issue of other plugins - imagine a user has installed 15 plugins then they each log errors into this file, the side effects would be:

- Too much details even for us (STDM devs) to sieve through.
- File size would be too big to manage.

For QGIS errors, it is better to run QGIS in debug mode and that way, all debug messages are logged.

If you need more details and control during your development, please have a look at the _First Aid_ plugin [here](https://github.com/wonder-sk/qgis-first-aid-plugin)

**Comment by wondie** [comment]
:+1:  I just imaged it :) . I will remove it on the next commit.

**Comment by wondie** [comment]
This issue is now fixed. I have removed it in [this commit](https://github.com/gltn/stdm/commit/1b30c385e16cb601bada57e730e6ff0e56298bd5).
