### ISSUE TITLE
Removing or changing the name of lookup tables already used by other tables not disabled

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#116]
The user can remove or edit lookup tables even if they are used and at the end of the wizard page, it shows the database error below, which is good. 
![image](https://cloud.githubusercontent.com/assets/9709624/16790832/b50f594a-48c1-11e6-8d46-1112fa3c4279.png)

But in my view editing are removing should be disabled for;

- any lookup tables being used by other entities
- any supporting document lookup tables

You can use this check but I don't know if there is a better way. 
```
        result = [
              True if 'lookup_name' in relation 
              else False 
              for relation in current_profile().relations
        ]
        if True in result:
            # your logic to disable editing and deleting
```

**Comment by pgathogo** [comment]
Fixed. Before deleting, wizard checks if a lookup is used by any column in all entities for the current profile.
