### ISSUE TITLE
All lookup values are listed when opening the columns and lookups page in the wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#118]
When I reach the columns and lookups page, all lookup values are listed in the values box. I hope this issue didn't come back due to the changes in the ui file. If the previous fix for [this issue](https://github.com/gltn/stdm/issues/73) was based on layouts, then, the layout variable names needs to be update.
![image](https://cloud.githubusercontent.com/assets/9709624/16796710/bbffae6e-48ec-11e6-9c32-32752424fd1f.png)

**Comment by pgathogo** [comment]
Fixed.
