### ISSUE TITLE
Adding auto backup of work progress on the configuraiton wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#119]
It would be wonderful to add an auto backup feature to a file preferably in the .stdm folder. In case of a failed wizard run, without losing anything,  the user can restore the failed profile and continue configuring. Also the user can send the failed configuration to developers so that the issue can be identified easily.

**Comment by gkahiu** [comment]
Hi Paul,

You save the temporary configuration prior to calling schema updater then delete it once the schema is successfully updated. 

In the case where the schema updating failed, then retain the file; next time the configuration wizard starts, have it search for this file first and if found then notify the user that there was pending schema updating session that did not complete successfully....The user will either have the option of re-using the cached configuration or disposing it.

**Comment by pgathogo** [comment]
Well noted.

**Comment by wondie** [comment]
The fix to this will be a bug fix because there is a related bug to this behavior of the wizard. 

When a User modifies an existing template with additional entities or columns, under normal conditions, a new column or entity is created in the database and the configuration.stc. However, if an error is shown while running the wizard, a new column or entity is created in the database but the change is not added in the configuration.stc. This will result in problems when trying to run the wizard again and add the same entities as they are not visible.

**Comment by wondie** [comment]
This feature is integrated and is working well. It has saved me already...
