### ISSUE TITLE
Duplicate key value violates unique constraint "content_base_name_key" after the wizard's successful compliton

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#121]
I got the error when I started working on a new profile with no other profile included in the config file and no table in stdm database. The error happened soon after the wizard finished when the modules were reloading using reaload_plugin() method. Below is the image. The error prevented reloading modules and after a restart, I couldn't login to STDM.

![image](https://cloud.githubusercontent.com/assets/9709624/16846322/a1e7de6c-49f4-11e6-8fbb-d94507927f04.png)

**Comment by wondie** [comment]
When I commented out [this line](https://github.com/gltn/stdm/blob/ref_config_mod/plugin.py#L618) and all associated methods, the error stopped showing. Do we use it?

**Comment by gkahiu** [comment]
It is not used, it refers to old code.

**Comment by wondie** [comment]
So shall I remove it completely? Also I see a [method ](https://github.com/gltn/stdm/blob/ref_config_mod/plugin.py#L1249)that seems to be related.  Shall I also remove it?

**Comment by wondie** [comment]
This issue is now fixed.
