### ISSUE TITLE
Sorting Configuration Wizard columns, entities, and value Not possible

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#122]
Note: @pgathogo You have not much to do here as the title suggests. :D
@pgathogo and @gkahiu I know sorting and re-ordering of items in the wizard that are added in the db or written to configuration.stc might be a bit difficult or imppossible. However, it could be possible to sort items also reflect in the database and configuration.stc before they are created. 

Currently, it is possible to change the order of items is by just editing them so that they are pushed to last in the list. As a default behavior it is good but this might not be desirable in some case. For instance, if a user has created 10 columns and wants the first one to be first_name. Then if he/she decides to make edits to first_name column after all columns are created, the first_name will be the last column. To make it the first column again, the user has to edit all others so that the first_name can be first in the list. This is a bit tedious. 

Considering the time I have, I decide to add a drag and drop sort feature so it is used by the Configuration Wizard. I add it under [utils/util.py](https://github.com/gltn/stdm/blob/ref_config_mod/utils/util.py#L711) so that other modules can use it. In addition to the wizard, this feature can enhance other modules such as Document Generator and the Import Wizard. I have already incorporated the feature in Document Generator in t[his commit](https://github.com/gltn/stdm/commit/ab8499531c90ca1acd8298c210755f8e3f4a547b) but I didn't incorporate it to the Import Wizard considering the time. It can be incorporated in STDM 2.0. 

I feel it would be great to incorporate the sort feature in the Configuration Wizard. You can implement it in the Entities creation page, the columns, and lookup values. 

The method is tested on QTableView and QListView so you just need to do the following to add it in the wizard. 

```

from stdm.utils.util import enable_drag_sort

# In a code block where you target new profiles with no configuration and db
enable_drag_sort(self.tbvColumns)
enable_drag_sort(self.lvLookupValues)
enable_drag_sort(self.pftableView)
```

**Comment by gkahiu** [comment]
Thanks Wondie for the comments and code snippets, indeed it is a feature
that I would like to see but my opinion is not to add it now. I have a
wishlist of many useful features but right now we should be on feature
freeze and focus on fixing bugs and documentation. The release candidate
release should have been out today and I would urge everyone to focus on
this, and packaging of the final release on Monday 25th July 2016.

Paul, my suggestion is not to include this but I leave the final decision
to you bearing in mind the release dates and making sure we avoid any
further delays.

Regards,

John

**Comment by wondie** [comment]
You are welcome John. I agree with you in focusing on fixing bugs. It would be good to include it only if there is time for Paul.

**Comment by pgathogo** [comment]
@wondie , great feature but to little time! I'll go with "feature freeze" option ... for now.

Regards,

Paul

**Comment by wondie** [comment]
Hi Paul, I understand you well. Lets leave it open for now.

**Comment by wondie** [comment]
This enhancement is incorporated.

**Comment by wondie** [comment]
The order set by drag and drop is not respected. After adding some columns and then saving the draft, the order get changed. I think there is still a problem with the default ordering. What I noticed is, newly created columns go to the top.

**Comment by wondie** [comment]
@pgathogo I found out that the ordering done is applied in the configuration file but when I load the Wizard again, it does not load the updated order. I though it is loading the order from memory but even if I restarted QGIS, the wizard does not load the as to the order in the configuration file.

**Comment by pgathogo** [comment]
@wondie , very true, the culprit is RenameableKeyDict.

**Comment by wondie** [comment]
This issue is fixed!
