### ISSUE TITLE
Mismatch in configuration.stc and Database columns/tables if an error is shown in the wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#123]
When a User modifies an existing template with additional entities or columns, under normal conditions, a new column or entity is created in the database and the configuration.stc.  However, if an error is shown while running the wizard, a new column or entity is created in the database but the change is not added in the configuration.stc. This will result in problems when trying to run the wizard again and add the same entities as they are not visible.

**Comment by gkahiu** [comment]
I believe this is linked to the enhancement for adding a cached
configuration?

**Comment by wondie** [comment]
The issue is related. It can be solved if the cached configuration loads as a default configuration. Otherwise, if the user ignore it, the mismatch will occur.

**Comment by gkahiu** [comment]
If related then please close this one and merge it with the other one.

**Comment by wondie** [comment]
That is noted. I will.
