### ISSUE TITLE
Name of 'wizardRun' Registry Key

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#124]
The case of 'wizardRun' registry key is in camel case and not consistent with the other keys, please revise it to 'WizardRun'.

**Comment by pgathogo** [comment]
Noted, will revert, but please note that I borrowed the style from other registry keys which are mostly camel case.

**Comment by pgathogo** [comment]
Fixed.

**Comment by gkahiu** [comment]
Thanks Paul for fixing this. It is only QGIS that uses camel case,
otherwise if you check your registry you will find other tools use title
case, which is the standard.

Regards,

John
