### ISSUE TITLE
Installing STDM 1.2 is not possible on QGIS 2.8

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#128]
When I tried to install STDM 1.2 on QGIS 2.8 by replacing the older version, I couldn't use STDM as they where incompatible. To solve the issue, I had to change the metadata.txt minimum version to 2.8. Shall I change it to 2.8 as STDM 1.2 supports 2.8 too?

**Comment by gkahiu** [comment]
If support for 2.8 is stable then update to metadata.txt is OK.
