### ISSUE TITLE
Editing Geometry and lookup Column results in a popup to select Column Property even though already set earlier

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#129]
Editing Geometry Column results in a popup to select Column Property even though it is already set in the previous wizard runs. 
Below is the error shown when the SRID is not re-set, even though it has values. 

![image](https://cloud.githubusercontent.com/assets/9709624/16952588/7d01b05a-4dd2-11e6-902e-19e4a6eacfeb.png)

The appearance of unmodified SRID looks like this. EPSG: is missing. 
![image](https://cloud.githubusercontent.com/assets/9709624/16952495/0c7a86cc-4dd2-11e6-9cc4-9ec5e68fad8c.png)

And when edited, it looks like this. EPSG: exists. 
![image](https://cloud.githubusercontent.com/assets/9709624/16952622/a6bf0244-4dd2-11e6-8fce-5a242264f2b5.png)

For lookup column, the error is the same but the value of the lookup table is properly set.

**Comment by pgathogo** [comment]
Fixed.
