### ISSUE TITLE
Foreign Key Mapper unable to add records

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#136]
The foreign key mapper is unable to add a selected record. It just adds an empty row with no data in it as shown below. 

![image](https://cloud.githubusercontent.com/assets/9709624/17132066/c937fece-5328-11e6-9b23-7995f9578f2b.png)

![image](https://cloud.githubusercontent.com/assets/9709624/17132082/e51db4d0-5328-11e6-95b3-5d67264545b0.png)

I have also noticed that Modules using the Foreign Key Mapper takes time to load. For instance, the New STR wizard only loads the person Foreign Key mapper but it still takes time. My guess is, there is some old code might be slowing it down.

**Comment by gkahiu** [comment]
It was my fault,i removed some code by mistake. Its fixed, will push.

**Comment by wondie** [comment]
That is noted. I will wait for the push.

**Comment by gkahiu** [comment]
Please check now. Should be fixed.

**Comment by wondie** [comment]
It is now fixed!
