### ISSUE TITLE
Issues with spatial capabilities in the entity browser

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#137]
I was working with a specific configuration where the spatial unit entity has two geometry columns (coz of different projections) and an error was being raised when I selected an existing record from the entity browser. This [code](https://github.com/gltn/stdm/blob/ref_config_mod/ui/entity_browser.py#L992) assumes that there is only one spatial column; for this to work, you need to handle multiple scenarios  including multiple geometries and also taking into consideration checking null values etc.

Another issue is the `zoom_to_layer()` function, what if there is no active layer in the canvas? 

Consider multiple scenarios.

**Comment by wondie** [comment]
I never imagined that a table could have two geometries. How can a user be able to digitize it? Is that even possible for QGIS?

The zoom_to_layer() will only be executed when there is a layer. Because, when a user launches Spatial Entity Browser, it will always add the entity's layer into the canvas. In addition, users cannot delete the layer as they only have access to the Entity Browser when it is open. Lastly, the closeEvent and hideEvent will only launch zoom_to_layer() when a the Entity has geometry.

**Comment by gkahiu** [comment]
Yes it is possible, and QGIS visualizes them as separate layers for each geometry column. As I indicated, the use case is geometry columns with different UTM projections for a country like Afghanistan which falls within three zones.

In my case, I have two geometry columns (UTM zone 41N and UTM zone 42N) so when I select a record in the entity browser the current code assumes there is spatial data in the first geometry column (which is not the case) and an exception is raised. See screenshots below:

![image](https://cloud.githubusercontent.com/assets/3840267/17139405/efaf1316-534c-11e6-8518-41255db76838.png)

![image](https://cloud.githubusercontent.com/assets/3840267/17139432/0c2e606e-534d-11e6-8441-bdf4d227195d.png)

**Comment by gkahiu** [comment]
Also for the activeLayer issue, I would strongly recommend that you check whether indeed there is an active layer first before zooming to its extents. I remember we talked about such kinds of checks.

**Comment by wondie** [comment]
I got the use case. What about digitizing a layer with two columns? When one select a layer and start digitizing, we can get the layers geometry column and we can add attribute information and the digitized geometry.  But how can we also add another geometry in the same row? Or is it like one row for geometry 1 another row for geometry 2?

**Comment by gkahiu** [comment]
In QGIS, each column is loaded as a separate layer. Similarly, in the
Spatial Unit Manager, the columns are listed as separate layers hence when
you digitize, the geometry goes to the spatial column in the current active
layer. So each row will only have one populated geometry column. The
question is how to manage them in the entity browser?

**Comment by gkahiu** [comment]
Please see the reference configuration [here](http://pastebin.com/x8ySLAYr).

**Comment by wondie** [comment]
I am able to reproduce the issue. The crash when opening attribute table is fixed. I will work on the entity browser and digitizing.

**Comment by wondie** [comment]
I have pushed the update. 

- Digitizing works for multiple geom columns. 

- Attribute table opens normally. 

- Opening of spatial entity browser leads to the addition of all layers of the table geometries. When  a user selects a row, it sets the column geometry layer active. Then, it tries to highlight the geometry. Currently, it works for one of the layers. But the second layer doesn't show the highlight. So I will work on it.

**Comment by gkahiu** [comment]
Great, I have a look at it. Let me know once you finalize.

**Comment by gkahiu** [comment]
I just tried it out:

   - The entity browser does not highlight the selected row for the second
   column (just as you have highlighted).
   - When digitizing the second column, the attribute form does not load.

Regards,

John

**Comment by wondie** [comment]
I have also noticed that. I will check it out. 

I noticed layerDisplay property in the configuration.stc. Is there anywhere in the wizard where users can set it?

**Comment by gkahiu** [comment]
I do not think there is an option of setting it in the wizard, only in the
spatial unit manager.

**Comment by wondie** [comment]
So does it mean when one set a display name in the spatial unit manager, it adds the that value in the configuration.stc?

**Comment by gkahiu** [comment]
Yes.

**Comment by wondie** [comment]
It would be great to add it in the configuration also but I think it is too late :D

**Comment by wondie** [comment]
I have fixed all the known issues. 

The main problem was, use two different projects in the same project. This made GIS not to properly work when using Highlight and digitizing. It seems like there is no good support in QGIS in this regard according to [this post.](http://gis.stackexchange.com/questions/25275/how-to-open-two-projects-at-once-in-one-qgis-window). If you check QGIS bottom right corner. When you even change your selection of layers, the SRID doesn't change. 

Thus I have incorporated a fix that will only allow one layer to load if it is from the same entity in [this commit](https://github.com/gltn/stdm/commit/5e3681d8406362a4aa32b4bcb4b4d06eaa2cc04a). In addition, I have added a code to update the map canvas SRID based on the layer. This solved the issue of highlights and digitizing. 

Please test it and inform me if you find an issue.

**Comment by gkahiu** [comment]
Hi,

The post you refer to is relates to a different issue; the person was asking if there is a way of opening two QGIS projects (with qgs file extension) at the same time which would then mean two different windows for each project. However, in our case we are not referring to projects but **projections**, and yes QGIS can overlay data with different projections as long as on-the-fly projection (OTF) is enabled (see highlight in the image below). The projection for the first loaded layer is taken to be the base projection then subsequent loaded layers are reprojected on-the-fly to the projection of the first loaded layer. So it is possible to perform spatial operations (select, highlight, measure distances, areas etc.) on multiple layers with different projections as long as OTF is enabled, which it should be by default.

![image](https://cloud.githubusercontent.com/assets/3840267/17204080/036cf110-54ac-11e6-81cd-0e37bba67ac2.png)

For me it comes down to the logic - if a row is selected by the user in the entity browser, find out the source of the geometry column (i.e. value is not None) then assert if the layer has already been loaded in the map; if yes, the just highlight the feature. If no, then load the layer then highlight feature.

Another question for further thinking - does this feature work in reverse i.e. if I manually select a spatial unit feature in the map canvas, will it also get selected in the entity browser when I open it? The QGIS attribute table provides this kind of support but am sure we cannot incorporate it now but might be good to ponder about it in the future.

Regards,

John

**Comment by wondie** [comment]
Oh I thought it was talking about projection. My bad. 
However, I have discovered that, highlighting works if I use this [method](https://github.com/gltn/stdm/blob/ref_config_mod/ui/entity_browser.py#L993). If you remove that method and load both layers, highlighting will not work. 
Unfortunately, the same method didn't help when digitizing, while both layers are in the map canvas. What happens is the following. 
1. Digitizing layer 1 goes ok
2. Digitizing layer 2 may or might not work. The geometry is invalid if it doesn't work.
3. Digitizing layer 1 again do not work.

**Comment by wondie** [comment]
Selecting a selection when a feature is selected is a cool feature. I think it is doable but if you think it is ok for now. :D

**Comment by wondie** [comment]
I discovered that, when layer is added through entity browser, it results in it not working properly when digitizing. Even for

**Comment by wondie** [comment]
There is a change in [this commit](https://github.com/gltn/stdm/commit/fb2f475cd7dfa484a90f2e90dda2d57b027e0687#diff-57d4c61f821545305ecd4c88fe28d854). As the issue of digitizing when using a layer by entity browser, I have replaced the close event remove behavior to zoom_to_layer.

**Comment by gkahiu** [comment]
Hi,

Am still experiencing issues with the entity browser with multiple geometries. The steps for reproducing are as follows:
1) I create my map by adding layers and styling them accordingly (see below).
![before entity browser](https://cloud.githubusercontent.com/assets/3840267/17326955/711d9dd0-58bd-11e6-95a7-6de206bf8c91.PNG)

2) Then once I load the entity browser for the given spatial entity, it first removes the previously styled spatial unit layer and also my map canvas becomes cleared (see below)
![after entity browser](https://cloud.githubusercontent.com/assets/3840267/17326991/b96b4cc2-58bd-11e6-8c4c-ca88ea574284.PNG)

3) I suspect it happens because the action of loading of the entity browser causes the canvas to zoom to the extents of the other geometry column that am not interested in.

Could you look into this and fix it before we branch off. I would rather we have more predictable behaviour then fix minor glitches later.

**Comment by wondie** [comment]
The reason that is happening because QGIS digitizing doesn't work with both layers from the same data source loaded. I have already asked this issue and there is no answer in gis.stakeexchange, one person commented that "QGIS is not built to handle mixed projections in the same datasource...".

So keeping both layers from the same table mean they will not work properly even if they are added from the spatial unit manager. The entity browser uses the same method of spatial unit manager. I can disable highlighting of features but the problem that you have reported will still exist when you add the other layer from the same table. I couldn't find a way out of this issue.

**Comment by wondie** [comment]
@gkahiu did you decide on this issue?

**Comment by gkahiu** [comment]
It seems to be fine for now with one geometry.
