### ISSUE TITLE
Name of Column Type in Configuration Wizard

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#138]
In the list of columns for a given entity, I would suggest that the names of the column types displayed be consistent with the names when they were being created otherwise it might be a little confusing and appear more technical. 

For example, when creating a _Related Entity_ column, in the table it appears as _Foreign key_ or _Varying-length Text_ appears as _Varchar_. It will be good if these names are consistent.

**Comment by pgathogo** [comment]
Column editor has been enhanced to show the Column.display_name().
