### ISSUE TITLE
Mismatch - deleting column removes it from configuration.stc but not from database

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#139]
When deleting a column even with no data, the wizard removes it from configuration.stc but not from database. This results in mismatch.

**Comment by wondie** [comment]
@gkahiu currently it is not possible to delete columns from the Configuration Wizard. Paul thinks it is related to the configuration. Could you please check it if you have time.

**Comment by gkahiu** [comment]
Fixed. Please test and confirm.

**Comment by wondie** [comment]
When I tried to remove gender_id column, I got the following error. 


```
(InternalError) cannot drop table lo_person column gender_id because other objects depend on it
DETAIL:  view local_government_vw_social_tenure_relationship depends on table lo_person column gender_id
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
 '\nALTER TABLE lo_person DROP COLUMN gender_id' {}
Failed to update configuration. Check error logs.
```

**Comment by gkahiu** [comment]
Is there existing data in the STR table?

**Comment by wondie** [comment]
IN STR table yes, but I was trying to delete in lo_person table.

**Comment by wondie** [comment]
Oh I just checked and there was no data in STR table.

**Comment by gkahiu** [comment]
If you try to delete a column that is referenced in a foreign key or in a
view , AND there is data then the deletion will fail. Unfortunately, those
PostgreSQL restrictions and similarly does not support this, so I need to
modify the DDL statement issued by SQLAlchemy so that it can include the
CASCADE keyword. For now, just put a warning in the documentation about
this limitation.

Regards,

John

**Comment by wondie** [comment]
That is noted. I will include that. So basically it means we can't delete columns of STR entities?

**Comment by wondie** [comment]
Is there any update on this issue?

**Comment by wondie** [comment]
@gkahiu I tested if the issue still exists. Unfortunately, it still exists. 
I deleted a column in the Configuration Wizard but the column is not removed from the database table. I was trying to remove a party column.

**Comment by wondie** [comment]
I tried to reproduce it today and this issue no longer exists so I am closing this issue.
