### ISSUE TITLE
The social tenure relationship page of the wizard is disabled for profiles with no database

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#140]
Users cannot choose party and spatial unit in the social tenure relationship page of the wizard as it is disabled. Disabling is not needed when there is no social tenure relationship table in the database. Relaying in the database makes it more flexible for the users to create a new db and change the party and spatial unit entities.

**Comment by wondie** [comment]
Now what happens is, even if social tenure relationship table exists, the option is enabled.

**Comment by pgathogo** [comment]
Hello Wondi,
The disabling of STR controls happens when the actual STR is defined and a record is created on the 'social_tenure_relationship'. So if the tables are created but STR has not been defined (in the STR wizard) then the controls are enabled.

Regards,

Paul

**Comment by wondie** [comment]
Hi Paul, this issue is not still fixed. So I have to re-open it. To reproduce the issue, delete the database that you are using. Then create it again. After this point, the str page is always enabled.

**Comment by pgathogo** [comment]
Wondi,

Please confirm that this item is fixed.

Regards,
Paul

**Comment by wondie** [comment]
@gkahiu it seems like there is an issue or limitation in removing relationships from the configuration.stc. The above post is also related to #151 Is it something that could be fixed?

**Comment by gkahiu** [comment]
@wondie , please confirm whether this issue is still valid?

**Comment by wondie** [comment]
@gkahiu I just checked by changing party entity and it is only changing in the configuration.stc not in the database. 

```
  <EntityRelation displayColumns="" child="social_tenure_relationship" parent="Planner" name="fk_lo_planner_id_lo_social_tenure_relationship_party_id" parentColumn="id" childColumn="party_id"/>
   <EntityRelation displayColumns="" child="social_tenure_relationship" parent="Parcel" name="fk_lo_parcel_id_lo_social_tenure_relationship_spatial_unit_id" parentColumn="id" childColumn="spatial_unit_id"/>
   <EntityRelation displayColumns="" child="social_tenure_relationship" parent="Planner" name="fk_lo_planner_id_lo_social_tenure_relationship_party_id" parentColumn="id" childColumn="party_id"/>

```

![image](https://cloud.githubusercontent.com/assets/9709624/18839644/638e862a-8414-11e6-9691-394a7c5c3df5.png)

Person should be changed by Planner but it is still person.

**Comment by gkahiu** [comment]
Did the social tenure relationship table exist before? If yes, then the
user should not be allowed to change it,infact the controls in the
configuration wizard should be disabled. If no,then it is a bug.

Could please confirm the situation as to whether the str table existed
before or not?

**Comment by wondie** [comment]
Yes it existed before.

**Comment by gkahiu** [comment]
If it existed before then it should not be interchangeable because of the
existing relationships and data model integrity.

**Comment by wondie** [comment]
Yes, a check is required to if str table exists, disable the selection...

**Comment by gkahiu** [comment]
@pgathogo , could you incorporate a check for the social tenure relationship table in the database and disable the controls in the STR config page in the wizard if an STR table exists?
