### ISSUE TITLE
Inconsistent behavior with 'OK' and 'APPLY' buttons of the options dialog

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#141]
Hello John,
I noted when you select a default profile in the options dialog, then click _APPLY_ button, a signal is emitted and the STDM plugin UI is updated accordingly to reflect the selected profile, but this is not the case when you select the _OK_ button. The dialog closes but the UI is never updated with the selected profile details.

Regards,

Paul

**Comment by wondie** [comment]
I have fixed the issue. I will commit when done with other changes.

**Comment by wondie** [comment]
This issue is now fixed in [this commit](https://github.com/gltn/stdm/commit/2f51c1c31423869078b027d8b83f3c81e942f744). @pgathogo could you confirm?
