### ISSUE TITLE
Opitions module window content's don't fit

### ISSUE THREAD

**Issue by eomwandho** [gltn/stdm#142]
Options window as shown below doesn't seem to fit its content.
![screenshot from 2016-07-28 17-55-49](https://cloud.githubusercontent.com/assets/2696951/17217513/46ff0db4-54ed-11e6-89da-9c3707110571.png)

**Comment by wondie** [comment]
Hi Erick, 

The issue is fixed on this [commit](https://github.com/gltn/stdm/commit/f725fb3401c79dbff2a40fdf5de7357a8117b6d3). Could you please check how it looks like now?

**Comment by wondie** [comment]
@eomwandho  how is the appearance of the Options window now?

**Comment by eomwandho** [comment]
Looks okay.
