### ISSUE TITLE
After DB is created, setting a column to mandatory has no effect in the database column

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#144]
Once the database is created without making a column mandatory, when I changed the column to mandatory in my next wizard run, the change is not updated in the database.

**Comment by wondie** [comment]
@gkahiu according to @pgathogo this issue seems to be related to the configuration, Could you please check it if you have time.

**Comment by gkahiu** [comment]
No its not related to the configuration, the edited column is not being
added to the list of updated colums for the given entity in
wizard.py hence, the column is not being flagged for updating in the
database. Also, the function edit_column in entity.py does not do anything
and i will remove it. The correct function that should have been used is
append_updated_column.

Am fixing it now then push.

Regards,

John

**Comment by wondie** [comment]
That is well noted. Thank you.

**Comment by gkahiu** [comment]
Fixed. Please test and confirm.

**Comment by wondie** [comment]
This issue is fixed.
