### ISSUE TITLE
Checkbox values are shown as True/False 

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#145]
Even though the value of True/False is the correct value, Yes/No is more common and quickly understandable for the users. So it would be good to change it to Yes/No. 
![image](https://cloud.githubusercontent.com/assets/9709624/17268228/91c0d2ec-562d-11e6-8034-c6cb51e838b2.png)

**Comment by gkahiu** [comment]
Resolved, will push it by the end of the day.

**Comment by wondie** [comment]
Ok great!

**Comment by gkahiu** [comment]
Resolved, please test and confirm.

**Comment by wondie** [comment]
This is now fixed!
