### ISSUE TITLE
What is the benefit of setSupportsList in ForeignKeyMapper 

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#146]
I wanted to know the benefit of ForeignKeyMapper  so that if it is not needed for the current modules using it (STR wizard and Document Generator), I want to set it True. 

This is comment found under setSupportsList.
```
        Sets whether the mapper supports only one item or multiple entities i.e.
        one-to-one (False) and one-to-many mapping (True).
```

**Comment by gkahiu** [comment]
Its for the number of items in the table. If set to True then multiple rows
can be added to the table, else if False then only one item can be added
such that if there is an existing item and the user chooses to add another
record then the existing item will be replaced.

**Comment by wondie** [comment]
That is a good feature! I will will use it for STR Wizard spatial unit and editing of STR.
