### ISSUE TITLE
Wrong Header File Information

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#147]
@wondie, I presume you created the file stdm/create_stdm_pro.py. However, the metadata in the file reads:

_Name                 : Register Parcel
Description          : GUI classes for managing and viewing supporting documents._

I believe this is copy/paste gremlin :-), please edit it accordingly.

Regards,

John

**Comment by wondie** [comment]
Ok thank you for the find. I will edit and push in few minutes.

**Comment by wondie** [comment]
The issue is now fixed by[ this commit. ](https://github.com/gltn/stdm/commit/b40e7a185e9a8b8214773288621fc2cc777df2f7)

**Comment by gkahiu** [comment]
Could you recheck the description?

**Comment by wondie** [comment]
Oh sorry. I just fixed it with [this commit ](https://github.com/gltn/stdm/commit/6173fedc8381261a9c009d6942ea01fc6bee40c7):)

**Comment by wondie** [comment]
@gkahiu is the header ok now?

**Comment by gkahiu** [comment]
Its good thanks.
