### ISSUE TITLE
Geomtry column name edit error

### ISSUE THREAD

**Issue by nkoech** [gltn/stdm#152]
This occurs when you try to edit a geometry column name in the configuration wizard. 

`Traceback (most recent call last):
  File "C:/Users/nkoech/.qgis2/python/plugins\stdm\ui\wizard\wizard.py", line 1479, in edit_column
    ref_column.copy_attrs(col)
AttributeError: 'NoneType' object has no attribute 'copy_attrs'`

**Comment by pgathogo** [comment]
This issues is associated with issue #156, which has been fixed this should also be fixed. Kindly confirm.
