### ISSUE TITLE
Very small lookup entity dialog buttons in the Configuration Wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#153]
It would be good to make the button sizes standard. Please see the image below. 
![image](https://cloud.githubusercontent.com/assets/9709624/17462206/5d44c32a-5cae-11e6-9473-c0440b0198f0.png)

**Comment by wondie** [comment]
@pgathogo how is the progress of this issue?

**Comment by pgathogo** [comment]
This is issue is fixed. @wondie , kindly test on your 'HD' resolution.

**Comment by wondie** [comment]
I have checked the dialogs. The lookup dialog is good. But the entity dialog is still smaller than normal. Please see the image below. 
![image](https://cloud.githubusercontent.com/assets/9709624/17975926/0d7aed66-6af4-11e6-9f84-a600a368e805.png)

The expected look is the following. 
![image](https://cloud.githubusercontent.com/assets/9709624/17975947/2540c362-6af4-11e6-806a-e9826372174f.png)

**Comment by wondie** [comment]
This issue is fixed.
