### ISSUE TITLE
DB errors after modifying column options

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#156]
I think the issue happens when the user edits the options of a column and run the wizard. In this case, I made first_name and other columns mandatory, column indexed. Then I got the errors below. This also happened during the training. It looks like changing the options of the column lead to the column being created much later than normal, that leads the to the error below. 
![image](https://cloud.githubusercontent.com/assets/9709624/17546597/a5a0fdf2-5eeb-11e6-8b72-8f81571a2eae.png)

Edit: When I re-run the wizard, it run successfully.

**Comment by pgathogo** [comment]
This issue has been fixed.

**Comment by pgathogo** [comment]
I have reopened the issue, issue not yet fixed.

**Comment by pgathogo** [comment]
Issue is fixed, kindly test.

**Comment by wondie** [comment]
I have confirmed that this issue is fixed!
