### ISSUE TITLE
How can we update old version document template to the new version?

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#157]
How can we update old version document template to the new version?

**Comment by gkahiu** [comment]
Good question. Well, we can write a script to update the referenced tables. However, the user will need to specify the 'referenced_data_source' attribute which in most cases is party if the view name has not changed. For custom views, then the user will have to do it manually. @wondie, it is something you can take up?

**Comment by wondie** [comment]
From what I understand, the updater first gets old tables and the corresponding new tables as a dictionary. Then the template updater scans and replace them in the template file. Is that possible to implement?

For the custom views, is it possible to have an option of adding more than one referenced tables so that users don't need to specify it?

I can take it up.

**Comment by gkahiu** [comment]
Yes, it can done sequentially, once the tables have been successfully updated then the templates updater can be plugged in to update the document templates as well.

For default views (which are based on the name) then the referenced data source can be automatically inserted, however for custom views am not sure how you can automatically determine which table was the primary reference?

**Comment by wondie** [comment]
As the custom views are based on the old tables, how can they be updated to use the new tables?

**Comment by wondie** [comment]
@gkahiu please ignore the above question. I already know the answer.

**Comment by wondie** [comment]
@gkahiu I got a way to get referenced table but it needs testing. It seems we have to scan through all templates in the template folder and update them and their views.

**Comment by wondie** [comment]
This issue is fixed with [this commit.](https://github.com/gltn/stdm/commit/f0204b15c6faa5d82c1e220521351f7a2b74dab6)
