### ISSUE TITLE
Newly created lookup entity not immediately showing in available lookup types

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#161]
On creating a new Single Select Lookup column and clicking column properties, I specify a new lookup name but on clicking OK, the lookup is not immediately added to the list but once I close the Lookup property window and re-open it again, the previously created lookup appears in the list. See illustration below:
1. Create new lookup
   ![image](https://cloud.githubusercontent.com/assets/3840267/18143621/9373db4a-6fcb-11e6-9c09-3bd52477a9fe.png)
2. Lookup does not immediately show in the list
   ![image](https://cloud.githubusercontent.com/assets/3840267/18143786/2f34dda4-6fcc-11e6-9424-fc9da8e88a38.png)
3. Lookup now available in the list after closing and re-opening the dialogue
   ![image](https://cloud.githubusercontent.com/assets/3840267/18143867/a5be4622-6fcc-11e6-9841-0c59f55da566.png)

Please review and confirm.

Regards,

John

**Comment by pgathogo** [comment]
Hello John,
I was unable to reproduce this issue on my environment, the lookup is showing up immediately after creation as expected.

Regards,

Paul

**Comment by pgathogo** [comment]
This issues has been fixed.
