### ISSUE TITLE
Make the GPS Points Importer a single page

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#164]
The GPS Points Importer takes the user through 3 pages. 
It starts with GPS path selection followed by list of GPS points and finally the STDM form. We can combine all the three pages as one to speed up the importing process and improve the user experience. 

The image below shows the suggested appearance of the GPS Points Importer. 

The following features and changes are expected.
- The interface integrates gpx file browser, points selector and Attributes Form in a tab interface as shown below. 
- The interface don't reset itself or close itself to allow multiple record entry in one go. 
- The module should detach itself from adding a layer as that is less obvious for the user. In stead, the user should choose an entity to import the data to in the Attribute Forms tab. This makes it easy for entry of records in case of multiple entity with different geometry. 

![image](https://cloud.githubusercontent.com/assets/9709624/18196976/664fb700-70fd-11e6-9ba3-cfb99ae8125e.png)

**Comment by gkahiu** [comment]
The UX is acceptable but with a few suggestions:

1. Change the title to be more descriptive e.g. Spatial Unit from GPX...
2. Lattitude column before Longitude column might be a little confusing, why not use X and Y
3. The title in Form tab is ambiguous, why not use something like Attributes etc.
4. Is there another column before Point Name?

**Comment by wondie** [comment]
1 is related to issue #163 :) 
2. I will fix that. The current interface is as shown above, there in Lat then Lon. 
3. That is noted. Is Attributes Form ok?
4. Yes, there is the checkbox column but it was not supposed to be that wide.

**Comment by wondie** [comment]
@gkahiu I have updated the first post.

**Comment by gkahiu** [comment]
@wondie , thanks for the update. It will also be good to include a feature for validating topology and highlighting topology issues based on geometry type. Let us discuss on Wednesday when we meet.

**Comment by wondie** [comment]
This feature is incorporated by @nkoech through [this pull request](https://github.com/gltn/stdm/pull/205) that is incorporated.
