### ISSUE TITLE
Renaming of entities in the wizard causes an error

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#165]
While creating a new profile, I configured all the entities with their corresponding columns and went back to the Entities page to edit the name of an entity which represented the Party in the profile configuration, which I successfully managed to do. However, on clicking finish to commit the new changes, an exception was thrown indicating that 'NoneType' does not have a 'name' attribute in the code `social_tenure.party.name`.

Hence, it seems like the renaming affected the configuration of this particular entity.

**Comment by pgathogo** [comment]
Issues is fixed.
