### ISSUE TITLE
Message when attempting to delete the one remaining profile

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#167]
![image](https://cloud.githubusercontent.com/assets/3840267/18199277/426a598e-7108-11e6-837b-dbe4ea50d148.png)

A couple of comments regarding this message:
1. The message icon should be critical/error because the operation is illegal.
2. There are typos in this message - 'atleast'...
3. I suggest a rephrase to something more descriptive like:
_'[profile_name]' cannot be deleted. At least one profile is required to exist in the STDM configuration...'_ however I leave this for you to decide.

Regards,

John

**Comment by pgathogo** [comment]
Profile delete message has been enhanced.

**Comment by wondie** [comment]
The message is enhanced but the dialog type is only warning not critical. It would be nice to make it critical.

**Comment by wondie** [comment]
I have closed the issue because @pgathogo explained that we can keep it as warning as users cannot actually delete the last profile as it is not allowed.
