### ISSUE TITLE
Defining STR Spatial Unit Entity in Configuration Wizard

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#168]
Two issues in the combobox for specifying the spatial unit entity:
1. It should only list those entities that have one or more geometry columns, not all entities as is shown below:

![image](https://cloud.githubusercontent.com/assets/3840267/18218061/f72e81fa-7168-11e6-9dbd-b71203aecec6.png)

2.In my current configuration, I have a profile which has got two entities with geometry columns respectively i.e. street and erf. However, the combobox seems to always select the first entity (street) irrespective of the setting previously specified in the configuration, where the second 'spatial' entity (erf) is the one that I had specified to be the spatial unit in the STR. In short, the spatial unit combobox does not respect the previously defined setting for the spatial unit in the STR.

**Comment by pgathogo** [comment]
Issues is fixed in branch 1.4.3
