### ISSUE TITLE
Multi-selection of Features to Spatial Entity Browser

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#179]
Currently, the Entity browser can select a feature when a record is selected. 

It is good to incorporate multi-selection of feature when multiple records are selected in the entity browser. 

This will lead to the change in use of QgsHiglight  to QgsVectorLayer.selectedFeatures() method.

**Comment by gkahiu** [comment]
This is a good addition as discussed during our meeting.

However, for the selection I would suggest that you do not preset the fill and border colors but let the selection be consistent with the colors QGIS uses for selection, this way the user can also change the colors for rendering selected features. 

QGIS selection colors are stored in the registry, please have a look at the following keys under QGIS/QGIS2/Qgis:
- default_selection_color_alpha
- default_selection_color_blue
- default_selection_color_green
- default_selection_color_red

**Comment by wondie** [comment]
That is true. It shouldn't be preset. Do you expect the addition of changing the selection color?

**Comment by gkahiu** [comment]
For just changing the selection color, not multiple selection of geometries.

**Comment by wondie** [comment]
QGIS already has an interface to change the selection color. Do we need to change it from STDM side?

**Comment by gkahiu** [comment]
What I meant is, the selection used in the view STR and highlighting
features in Entity Browser for spatial features should use the same colors
as those used by QGIS selection. So incorporate the use of uniform colors
in master then multiple geometry select can be implemented once we have
branched off.

**Comment by wondie** [comment]
Unfortunately, I couldn't find a way to know the selection color QGIS is using. I could only get the [highlight color](https://qgis.org/api/classQGis.html#addfdebf810e932b355e665118b00d530) which is different.

For now, the colors used in STR and Entity browser selection are the same. We can stick with it for now and change it to layer.selectedFeature() method to highlight features in the next versions.

**Comment by wondie** [comment]
However, I can use photoshop to get the RGB color and hard code it for now. Is that ok for now?

**Comment by wondie** [comment]
Ok I got the color from option. I will change and push now.

**Comment by wondie** [comment]
I am able to use the registry key that you posted early. I have pushed the change in [this commit](https://github.com/gltn/stdm/commit/017f7a92311d49ad79a455b2a116fe09c3fc2e86). I have added a method called selection_color() inside registryconfig.py

**Comment by gkahiu** [comment]
Consider using the alpha channel as well so that you initialize the color
object as:

QColor.__init__ (*self*, int *r*, int *g*, int *b*, int *alpha* = 255)

Regards,

John

**Comment by wondie** [comment]
That is noted. I will do that later.

**Comment by wondie** [comment]
@gkahiu I have added the alpha channel in[ this commit.](https://github.com/gltn/stdm/commit/3927828dcfd5fcb747e2f5eaf46b53c244b0eca9) The QColor.__init__ didn't work for me though. QColor(r,g,b,a) worked though.

**Comment by wondie** [comment]
This feature is included in STDM 1.5 and can be found in master.
