### ISSUE TITLE
The ability to create a draft profile with no database in the Configuration Wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#180]
The creation of a profile could take time. In addition, the ability to modify profiles once the database is created is restricted. The ability to create a draft profile with no database gives the user more flexibility to: 
- rename entities
- change profile names
- re-name columns
- change entities participating in STR.

**Comment by pgathogo** [comment]
This feature will be included in release 1.5.

**Comment by gkahiu** [comment]
@pgathogo thanks for the update. When do you expect to merge it so that we can comprehensively text it?

**Comment by wondie** [comment]
This feature is merged in master with [this commit](https://github.com/gltn/stdm/commit/7cf3b8a54aa9c56a5898634b7c006f46c6f75050).
