### ISSUE TITLE
Issues with adding and editing lookup values

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#183]
When editing a lookup value, the edited value is kept in the database and the new edit is created as a new value. But in the configuration wizard, the old value is hidden which gives a feel that the value is editing but a new copy is created. 

The other issue is adding a lookup value that is long is accepted in the configuration but not in the database and this leads to a miss-match in the Configuration Wizard and the database. 

This issue leads to a miss-match in the lookup value in the configuration wizard and the database table. 
![image](https://cloud.githubusercontent.com/assets/9709624/18909240/885b1582-857b-11e6-866d-d3b163a9dd3c.png)

![image](https://cloud.githubusercontent.com/assets/9709624/18909265/a202b03a-857b-11e6-9299-4db06ecced22.png)

**Comment by gkahiu** [comment]
@pgathogo , i had a look at this and noticed that you are removing the old value and adding a new value based on this code [here](https://github.com/gltn/stdm/blob/master/ui/wizard/create_lookup_value.py#L84), however I stand corrected. When editing existing lookups, please use the `rename` function in the ValueList object, see reference [here](https://github.com/gltn/stdm/blob/master/data/configuration/value_list.py#L157).

Another recommendation is you limit the number of characters in the lookup value editor to a maximum of **50** characters for the value and **5** characters for code. See the column constraints [here](https://github.com/gltn/stdm/blob/master/data/configuration/value_list.py#L75)

**Comment by pgathogo** [comment]
Renaming of lookup values is fixed.

**Comment by wondie** [comment]
I just tested it. The character length is limited to 50 and I was able to save 50 Character value. 

However, renaming still results in a new lookup.
I renamed **Utility Bills** to **Bills** but it doesn't re-name, it keeps the old value and makes the edited value to be a new value. Please, see the image below. 
![image](https://cloud.githubusercontent.com/assets/9709624/18965542/5aeedb40-8686-11e6-8598-c529e59f9ed5.png)

**Comment by pgathogo** [comment]
@wondie , thanks, I think I'll have to escalate this to @gkahiu.

**Comment by gkahiu** [comment]
Fixed in d41d4fe. Please test and confirm.

**Comment by wondie** [comment]
It is working now! :+1:
