### ISSUE TITLE
The Configuration wizard has failed to create a database

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#185]
The Configuration wizard has constantly failed to create a database. When I run it, it jus hangs. I tried different configurations including the default configuration. I also tried different new databases but the result is the same. 
@pgathogo and @gkahiu this issue might also affect the 1.4 release as configuration related commits are merged to the 1.4 branch.

**Comment by gkahiu** [comment]
I tested in the rel-1_4_0 and it is working fine unless there is a specific configuration option that is causing it to fail.

**Comment by wondie** [comment]
Any configuration that used to work before is not working. I also restarted my machine but it didn't work still.

**Comment by pgathogo** [comment]
Dear Wondi,

How many databases do you have on your PostgreSQL?

Regards

Paul

**Comment by wondie** [comment]
Dear Paul,

I originally had about 10. Now I have about 4. But the issue still exists.

**Comment by wondie** [comment]
This issue is fixed after installing upgrading to PostgreSQL 9.5 from PostgreSQL 9.4.
