### ISSUE TITLE
Same Multiple Layers Added in View Social Tenure Relationship

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#186]
When I load the View Social Tenure Relationship module, it automatically loads the layer corresponding to the spatial unit in the current profile. When I close the window and reload it again, it add the same layer again and it does the same thing for each subsequent load. Consequently, the TOC ends up with the (same) multiple layers whose number is equal to the number of times the view social tenure relationship window has been loaded.

Can you devise a mechanism for checking if the spatial unit layer already exists in the TOC prior to adding the layer when a user loads the View Social Tenure Relationship window?

**Comment by wondie** [comment]
There was supposed to be a mechanism to check. I will check and fix it

**Comment by wondie** [comment]
@gkahiu does this issue still exist on your side?

**Comment by wondie** [comment]
This issue is now fixed. Please test and confirm.
