### ISSUE TITLE
Creating a column and canceling the wizard causes mismatch error in different modules

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#187]
This issue happens when a user creates a profile and closes the Wizard without saving by clicking on the Finish button. I guess when the user cancels, the profile is already updated in the memory and this results in a mismatch of columns in the database and the profile object. 

In my view, the profile object in memory should not be updated until the user clicks on the Finish button. When a cancel button is clicked, nothing should be saved.

**Comment by pgathogo** [comment]
Dear Wondi,
Kindly explain what you mean by 'mismatch' error on other modules?  Might this be related to the issue you are experiencing for saving the profile in the database?

Regards,

Paul

**Comment by wondie** [comment]
Dear Paul,

When I say mismatch error, the previously added and removed column due to wizard cancellation still exists in the current profile object. When I load entity browser, STR wizard, Documents Generator, they all assume the column exists in the profile but doesn't exist in the database and the show an error message that there is a mismatch in the current profile entity columns and the database table columns.

**Comment by pgathogo** [comment]
Dear Wondi,
What am thinking is, if we fix issue #185 that you reported earlier, then this issue might also get resolved.

**Comment by wondie** [comment]
Dear Paul,

I hope so too even though their nature is different.

**Comment by wondie** [comment]
This issue doesn't exist anymore.

**Comment by wondie** [comment]
@pgathogo and @gkahiu I got this issue again. I now know how to reproduce it. The issue is, when columns are created and there is a db error in Configuration wizard, the columns are still added in profile object without having a matching column in the database. That is why the error above happens. 

To reproduce it, follow the steps below. 
1. In an existing entity that has data, add a new column, set it as Mandatory in column editor. 
This leads to a database error in the wizard. 
2. Now go to the Entity Browser of the same entity in which you failed to add the column. 
3. You should get an error on a mismatched columns. 

I think the cause of this issue is the wizard adds new columns etc to the current profile. Even if the wizard fails it doesn't clear these changes from the memory.

**Comment by gkahiu** [comment]
@pgathogo please advise on whether to roll back to the original configuration by requesting the user to rollback or re-edit the configuration.

**Comment by wondie** [comment]
This issue is fixed by [this commit](https://github.com/gltn/stdm/commit/d4b323b6829829fdbaeafb36b9838b5c505e2c6b).
