### ISSUE TITLE
Error Reading GLTN Plugin Repository

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#189]
The error message shows the repository is moved permanently. If it is moved, I feel it will make it more difficult for the users to upgrade. Why couldn't we keep the existing link?
![image](https://cloud.githubusercontent.com/assets/9709624/19415795/820f029e-9384-11e6-9112-7c5279ee9d24.png)

**Comment by gkahiu** [comment]
I will have a look at it when uploading the revised plugin repository
settings. The links have not been moved as far as I know, have a look at it
again once the official announcement has been made.
