### ISSUE TITLE
Installation STDM Guide version 1.0 needs update

### ISSUE THREAD

**Issue by vioannidi** [gltn/stdm#19]
If a new user tries to install STDM version 1.0 (including PostgreSQL PostGIS, QGIS), by using the installation file "STDM-1.0-Final-x86.exe" and consulting the guide at the same time, then he/she gets confused because on page 6 of the guide it reads that a template database needs to be created by using the "STDM-v1-Restore-Schema.exe" file. This file is nowhere to be found and the steps described in the guide after this point are not in line with this version. According to John Gitau (I have been in contact with him about the installation of STDM this week) the version 1.0 of the installer does not require a restoration of the schema.

**Comment by gkahiu** [comment]
Updates ongoing and will be synced with the release of v1.1
