### ISSUE TITLE
Unlimited Text and Administrative Unit Column Type are disabled even if DB tables don't exist

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#192]
Unlimited Text and Administrative Unit Column Type are disabled even if DB tables doesn't exist in the column editor. 

![image](https://cloud.githubusercontent.com/assets/9709624/19726257/b3b48448-9b92-11e6-8bd9-c4d6484e1db4.png)

**Comment by pgathogo** [comment]
@wondie , they behave like that by design.

**Comment by wondie** [comment]
@pgathogo Could you explain the design?

**Comment by wondie** [comment]
The explanation is obtained from @pgathogo in person. The reason why it is disabled is because the two column types have no column properties.
