### ISSUE TITLE
How could I determine the order of entities in the configuration and Entities menu

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#194]
I wanted to order entities logically in the **Entities menu** and Entities page of the configuration wizard. I sorted the order of the entities in **configuration.stc** but the changes are not reflected. Is there any way or changing the order of entities?
![image](https://cloud.githubusercontent.com/assets/9709624/19775263/8f6dc9aa-9c78-11e6-9eba-afac93450c6b.png)

**Comment by gkahiu** [comment]
Currently there isn't an option of doing so.

Regards,

John

**Comment by wondie** [comment]
For the old version, it was possible to sort the order of entities based on the order in the configuration file.   I think entities are kept in OrderedDict, why is it not possible to order?
