### ISSUE TITLE
The version number is not showing in the About STDM module

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#196]
The version number is not showing in the GLTN plugin repository version. 
![image](https://cloud.githubusercontent.com/assets/9709624/19816868/c18df2be-9d51-11e6-8ca4-76f2766901ca.png)

**Comment by gkahiu** [comment]
That's very strange, I'll check and revert.

**Comment by wondie** [comment]
I just discovered it is the same for the installer version too.

**Comment by wondie** [comment]
I still have this issue.

**Comment by wondie** [comment]
The QGIS way of getting version number is not working. Thus, I fixed the issue with the addition another method that reads the metadata and gets the version number.
