### ISSUE TITLE
Adding Administrative Units in the configuration.stc

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#197]
The administrative units are only stored in the database. In addition, there is no way of backing up the admin_spatial_unit_set in the Export module. This makes it difficult when there is a change of database as for most users, the administrative unites have to be re-entered. 

This can be solved if addition of the administrative units are saved in the configuration.stc as a global node so that it can be accessible for all profiles.

**Comment by gkahiu** [comment]
Well it is doable but i would consider it low priority for now compared to
the level of effort required to integrate it.

The values do not have to be re-entered if migrating databases, users can
just backup this specific table and restore it, that should not be
difficult.
