### ISSUE TITLE
UnicodeDecodeError when starting STDM

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#198]
This computer has US English set as default windows language but there are other languages set too.  QGIS also use US English. As a result of this error, I couldn't start it. 
```
Couldn't load plugin 'stdm' 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 17: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISES~1.8)F/apps/qgis/./python\qgis\utils.py", line 281, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGISES~1.8)F/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/�garen/.qgis2/python/plugins\stdm\__init__.py", line 40, in 
    if third_party_dir not in sys.path:
  File "C:/PROGRA~1/QGISES~1.8)F/apps/qgis/./python\qgis\utils.py", line 58, in showWarning
    "warning:%s\ntraceback:%s" % (warnings.formatwarning(message, category, filename, lineno), stk),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 17: ordinal not in range(128)


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.8-Essen Essen, exported 

Python Path:
C:/PROGRA~1/QGISES~1.8)F/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGISES~1.8)F/apps/qgis/./python
C:/Users/Ägaren/.qgis2/python
C:/Users/Ägaren/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1.8)F/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGISES~1.8)F\bin\python27.zip
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1.8)F\bin
C:\PROGRA~1\QGISES~1.8)F\apps\Python27
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1.8)F\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Ägaren/.qgis2//python
C:\PROGRA~1\QGISES~1.8)F\apps\qgis\python\plugins\fTools\tools
```

**Comment by gkahiu** [comment]
It is not related to the language. It is related to the user account name i.e. `Ägaren` where the first character `Ä` is non-ASCII. Could you try and convert `third_party_dir` variable to unicode as follows:
```
third_party_dir = unicode(os.path.abspath(os.path.join(os.path.dirname(__file__),
                                               "third_party")))
```

Let me know.

**Comment by wondie** [comment]
Unfortunately it is not working still.

**Comment by gkahiu** [comment]
Using the QGIS python console, can you type the following:

import sys

sys.path

Send me the value you get from sys.path - should be a list containing
multiple string items.

**Comment by wondie** [comment]
`['C:/PROGRA~1/QGISES~1.8)F/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~1/QGISES~1.8)F/apps/qgis/./python', u'C:/Users/\xc4garen/.qgis2/python', u'C:/Users/\xc4garen/.qgis2/python/plugins', 'C:/PROGRA~1/QGISES~1.8)F/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISES~1.8)F\\bin', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/\xc4garen/.qgis2//python', 'C:\\PROGRA~1\\QGISES~1.8)F\\apps\\qgis\\python\\plugins\\fTools\\tools']`

**Comment by gkahiu** [comment]
I was able to reproduce the issue in my Python console. As suspected, the issue is brought about by a mix of str and unicode objects in `sys.path`. There are multiple options but try this for starters - at the very top of `...stdm\__init__.py`, add the following lines:
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```

Hence, the beginning should read like this:
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
/***************************************************************************
Name                 : Social Tenure Domain Model
Description          : QGIS Entry Point for Social Tenure Domain Model
Date                 : 04-01-2015
copyright            : (C) 2015 by UN-Habitat and implementing partners.
                       See the accompanying file CONTRIBUTORS.txt in the root
email                : stdm@unhabitat.org
 ***************************************************************************/
...
```

Let me know if this resolves it.

**Comment by wondie** [comment]
I added it but the error is still showing.

**Comment by wondie** [comment]
This error is related to QGIS. So it can't be solved by STDM. If the issue happens, the issue can be fixed manually or as a work around, it is good to install STDM in a user account with no accents or diacritics such as João, Ägaren, etc. Instead, use Joao, Agaren.
