### ISSUE TITLE
Duplicate importing after SQL error

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#199]
When a user imports data and there is an SQL error, some rows are already imported and when the user re-imports after fixing the issues, a duplicate for an existing rows exist. Is there any way of using a transaction and rollback in case of an error?

**Comment by gkahiu** [comment]
Probably a pre-check mechanism for validating the data before importing which could validate uniqueness, mandatory fields, geometry types, data encoding etc.

**Comment by wondie** [comment]
Yes, that is true.

**Comment by nyalldawson** [comment]
This was fixed by https://github.com/gltn/stdm/pull/416
