### ISSUE TITLE
Disable Drag and sort for Entities in the Configuration Wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#201]
[According to John](https://github.com/gltn/stdm/issues/194), the order of entities cannot be determined by drag and drop and creation order, due to dependency when creating tables. Until an Entity attribute order is created, the drag sort feature has no use for Entities. 

More over, mismatch in the index or sorted entities is found so, we need to disable it in the upcoming patched release. Lookup values and Columns have no problem and the feature works for them, so we can keep it for them. 

[This ](https://github.com/gltn/stdm/blob/master/ui/wizard/wizard.py#L1614)and [this ](https://github.com/gltn/stdm/blob/master/ui/wizard/wizard.py#L1618)lines need to be removed to apply the bug fix and enhancement.

**Comment by pgathogo** [comment]
Fixed in branch 1.4.3
