### ISSUE TITLE
Failed to create index (column indexed) for long column

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#202]
I tried to set column indexed option for a long column and resulted in the following database error when running the Configuration wizard. 

```
Preparing configuration, please wait...
Configuration update started...
Scanning for changes in Uganda_Customary profile...
Removing redundant foreign key constraints...
Deleting Clan entity...
Creating check_social_tenure_relationship_document_type entity...
Creating social_tenure_relationship_supporting_document entity...
Creating check_tenure_type entity...
Creating supporting_document entity...
Creating admin_spatial_unit_set entity...
Creating social_tenure_relationship entity...
Creating check_sex entity...
Creating check_landuse entity...
Creating check_marital_status entity...
Creating check_portion_type entity...
Creating check_dispute entity...
Creating check_person_document_type entity...
Creating check_application_approval_document_type entity...
Creating check_approval_status entity...
Creating check_position entity...
Creating check_adjudication_document_type entity...
Creating check_household_document_type entity...
Creating check_recorder_document_type entity...
Creating check_clan entity...
Creating check_community entity...
Creating Physical Planner entity...
Creating Recorder_supporting_document entity...
Creating Recorder entity...
Creating Person_supporting_document entity...
Creating Person entity...
Creating Application_approval_supporting_document entity...
Creating Application_approval entity...
Identifier 'idx_ug_application_approval_district_land_board_meeting_minute_number' exceeds maximum length of 63 characters
Failed to update configuration. Check error logs.
```

Is there any fix for this issue without shortening the column?

**Comment by pgathogo** [comment]
@wondie , IMHO, it is bad practice to have very long column names for a table, if a user wants a descriptive name for a column, we have provided a `description` field for that purpose.
To avoid this kind of problems or any other that might be associated with long column names, am enforcing a maximum length of 40 characters per column name.

Best regards.

**Comment by wondie** [comment]
@pgathogo that is a good point, I agree with ristricting the character legth in postgres. We can restrict it as per PostgreSQL specification [discussed here](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS).  The character limit is 63 characters.

**Comment by pgathogo** [comment]
@wondie, am finding 63 characters a bit to much for a user defined column name. PostgreSQL allows this length for flexibility reasons, especially if the column is automatically generated by some system and consumed internally by some other system. But for human facing system, 63 character long column name looks quite odd. 

Regards,

**Comment by wondie** [comment]
@pgathogo It could look quiet odd but what if the user wants it? Why do we limit users while PostgreSQL can do it?

**Comment by pgathogo** [comment]
@wondie , We can now close this issue after we agreed to limit the length of the column name to a max of 40 characters.

Regards.
PG

**Comment by wondie** [comment]
@pgathogo we couldn't close it as the issue is not character length but the problem of not truncating the index length without showing the above error.

**Comment by nyalldawson** [comment]
@gkahiu Your commit https://github.com/gltn/stdm/commit/8d22437a7e3bab2078e7654e023c525905ceb697 should fix this too

**Comment by gkahiu** [comment]
Yes I believe it should fix it. Will close it for now.
