### ISSUE TITLE
In ability to save STR due to dynamic party columns

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#207]
This issue is caused by the addition of multiple party entity in STR table. This resulted in change of party_id to entity_short_name_id. This brings me back to [this issue](https://github.com/gltn/stdm/issues/57) which was solved by removing the profile prefix. Is there any solution for this one?

**Comment by gkahiu** [comment]
What's the exact issue?

**Comment by wondie** [comment]
The issue is the following. Previously, I was able to save STR because I know all columns and as a result, I use this method.
```
            str_obj = self.str_model(
                party_id=party_id,
                spatial_unit_id=str_store.spatial_unit.keys()[0],
                tenure_type=str_type_id
            )
```
Now, there is no more party_id, which is logical as there could be more than one party. However, not knowing the column prevents me from using the above method. Instead, I have to use this method.
`setattr( self.str_model, '[column_name]', party_entity_obj.id)`. Unfortunately, this method doesn't work in saveMany() as explained in [this issue](https://github.com/gltn/stdm/issues/57).

**Comment by wondie** [comment]
The issue is fixed using argument packing and unpacking. Thank you John!
