### ISSUE TITLE
The percent column doesn't show the % in Spatial Entity Details

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#208]
The percent column doesn't show the % in Spatial Entity Details as shown below. 
![image](https://cloud.githubusercontent.com/assets/9709624/22060346/6b3c5db8-dd81-11e6-8e90-74cccda66290.png)

**Comment by gkahiu** [comment]
The % suffix is in the input widget (in the entity editor dialog) as i had
indicated, not in the database value since it is stored as a decimal value.

Regards,

John

**Comment by wondie** [comment]
Ok noted.
