### ISSUE TITLE
"Spatial Unit" module is missing from the STDM Modules list

### ISSUE THREAD

**Issue by vioannidi** [gltn/stdm#21]
Although the table spatial_unit exists in the stdm profile and I can see it back in the stdm database in postgreSQL, there is no module Spatial Unit in the STDM Modules list (in this list there are only the Household, the Supporting Document, the Party and the Social Tenure Relationship (STR)). That means that I cannot create spatial units to connect them through the STR form to a party. 
I am working with the stdm-plugin in QGIS 2.4.0 that I downloaded as zip file from here: https://github.com/gltn/stdm-plugin

**Comment by SolomonN** [comment]
Hi,Yes spatial unit table exist in the stdm database and not available in the module list.The intention is to separate spatial tables with attribute tables. So, to edit the spatial table, you access them using Add postGIS layer command in QGIS layer menu and load them normally you do with any other postGIS layer. A new connection to STDM database is required to access the geometry tables. The connection parameters are the same as those used to login to STDM plugin.



 Kind Regards,
Solomon.Mobile +254 724 291046 

     On Saturday, February 28, 2015 12:59 AM, vioannidi <notifications@github.com> wrote:
   

 Although the table spatial_unit exists in the stdm profile and I can see it back in the stdm database in postgreSQL, there is no module Spatial Unit in the STDM Modules list (in this list there are only the Household, the Supporting Document, the Party and the Social Tenure Relationship (STR)). That means that I cannot create spatial units to connect them through the STR form to a party. 
I am working with the stdm-plugin in QGIS 2.4.0 that I downloaded as zip file from here: https://github.com/gltn/stdm-plugin—

**Comment by eomwandho** [comment]
Is this functionality similar to what the spatial unit manager will achieve?

**Comment by gkahiu** [comment]
For now, please ignore this issue because the Spatial Unit Manager
addresses some of the required functionality.

John
