### ISSUE TITLE
Couldn't define STR tables in the configuration wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#211]
I tried to create a new profile by creating two party entities. Then when I reached the STR page, I couldn't set both the party and spatial unit entities. They are both disabled.

![image](https://cloud.githubusercontent.com/assets/9709624/22308106/a6839fe6-e356-11e6-8ec5-cc21c34d68bf.png)

**Comment by gkahiu** [comment]
This can only happen if there is an existing STR table with the same name. What is the name of you profile, what is the prefix? Is there an existing table in the database with the name corresponding to:
```
str_table_name = profile.prefix + '_social_tenure_relationship'
```

Cheers!

**Comment by wondie** [comment]
That is the cause of the problem. I had a profile called **Test_profile** and I tried to create a profile called **Test2**. Both were not supposed to have the same prefix as the prefix creator method should have chosen a unique prefix. If it is not possible to fix it, it would be good to notify the user to change the profile name if the profile prefix already exists.

**Comment by wondie** [comment]
@pgathogo the issue is that the method curr_profile.prefix used [here ](https://github.com/gltn/stdm/blob/master/ui/wizard/wizard.py#L976) is not properly executed. However, when I print something above it, it works. So the solution is just to add 
` QApplication.processEvents()`at [this line](https://github.com/gltn/stdm/blob/master/ui/wizard/wizard.py#L972) just before the str table is determined.

**Comment by gkahiu** [comment]
I think the validation code is in the wrong section, it should be under the _initializePage_ function override. Just give it a try and let me know.

**Comment by wondie** [comment]
This issue is now fixed by moving the code into `initializePage `as suggested.
