### ISSUE TITLE
Unique constraint coluldn't be added when setting it in the configuration wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#214]
I created a profile and after creating the tables by running the wizard, I added a column with unique option but the constraint couldn't be added. 

**Edit**: I also tried with empty db and the result is the same.

**Comment by gkahiu** [comment]
I will check and revert.

**Comment by gkahiu** [comment]
I could not replicate your issue, I have successfully created a unique constraint for a varying-length character column type with the details as shown below:
![image](https://cloud.githubusercontent.com/assets/3840267/22957347/beb6ee00-f338-11e6-8220-18e8583c6642.png)

The resulting constraint in the database:
![image](https://cloud.githubusercontent.com/assets/3840267/22957395/08943190-f339-11e6-8c5d-929a95a028ae.png)

And configuration setting:
![image](https://cloud.githubusercontent.com/assets/3840267/22957443/4cd32776-f339-11e6-9697-c4f1cd2060d4.png)

Regards,

John

**Comment by wondie** [comment]
That is good. I think this issue might be related to issue #215. Let me close this issue for now and see if it re-occurs.
