### ISSUE TITLE
The Configuration Wizards becomes unresponsive intermittently

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#215]
I have been having an intermittent DB hanging issue. I decided to check the pg_log and this is what I found. 

```
2017-02-11 22:20:47 CAT LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.

	
2017-02-11 22:20:47 CAT LOG:  unexpected EOF on client connection with an open transaction
2017-02-11 22:20:47 CAT LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.

	
2017-02-11 22:20:47 CAT LOG:  could not send data to client: An existing connection was forcibly closed by the remote host.

	
2017-02-11 22:20:47 CAT FATAL:  connection to client lost
```

**Comment by wondie** [comment]
The issue don't appear as soon as I re-run the wizard.

**Comment by gkahiu** [comment]
The error log message basically shows that the remote end (PostgreSQL server) has terminated the socket. The 'forcibly" just means it was done in an unusual way but it is still the remote end. 

From a quick desk study, it is either caused by a Windows firewall setting (so you might want to check Windows logs) or the database connection timed out, so you might want to check out the _connect_timeout_ and _keep_alives_ PostgreSQL parameters (see reference [here](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS)) and see if they will resolve the issue, besides this I have no other solution I can think of.

**Comment by wondie** [comment]
I think the later reason could be the cause. I have 6 profiles. That is why it is taking longer. Is it possible to increase the timeout from the schemaupdater or in the installer?

**Comment by gkahiu** [comment]
This is a PostgreSQL setting so it can only be set manually or (maybe) through the connection string which I have not tried yet. 

But first try changing it manually via PostgreSQL configuration file (then restart service) and try reproduce the issue; if changing the connection properties resolves it then we can decide on how to integrate the workaround into the tool.

**Comment by wondie** [comment]
I just tested it and it has a positive effect in the Configuration Wizard. The wizard no longer hangs even temporarily. I couldn't find the timeout setting inside postgres configuration files but I found a query that does it. 
`SET SESSION STATEMENT_TIMEOUT TO 0;` This code sets the connection timeout to unlimited timeout. 
There is also a way to do it in SQLAlchemy according to[ this answer](http://stackoverflow.com/questions/35640726/how-to-set-connection-timeout-in-sqlalchemy?answertab=votes#tab-top). I think something around 15000 (15 seconds) is good for the tool.

**Comment by gkahiu** [comment]
Please go ahead and edit the engine properties [here](https://github.com/gltn/stdm/blob/master/data/connection.py#L56) then test if it works.

**Comment by wondie** [comment]
That is noted.

**Comment by wondie** [comment]
@gkahiu I discovered that setting the statement_timeout is not recommended according to this page - https://www.postgresql.org/docs/9.5/static/runtime-config-client.html

> Setting lock_timeout in postgresql.conf is not recommended because it would affect all sessions.
So I have to set it to 0 so that it is unlimited. I hope that is ok.

**Comment by gkahiu** [comment]
I thought its already zero by default?

**Comment by wondie** [comment]
I don't think so. If that was the cause, I wouldn't have seen an intimidate effect as pointed out [here](https://github.com/gltn/stdm/issues/215#issuecomment-279343931).

**Comment by gkahiu** [comment]
So the issue is now resolved?

**Comment by wondie** [comment]
Yes. I issue closed.
