### ISSUE TITLE
Entity order misaligned when editing entity

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#219]
Entity order misaligned when adding new entities and adding description. 

Please see the image below. What is selected is productivity but it is loading impact entity for editing. 
![image](https://cloud.githubusercontent.com/assets/9709624/23362720/279b45e6-fd08-11e6-8499-ac4f4c7ac6c6.png)

**Comment by wondie** [comment]
It looks like there is error in the index. When I edit Impact, is loads Priority entity.

**Comment by pgathogo** [comment]
@wondie, am unable to reproduce the issue from my end.

**Comment by wondie** [comment]
@pgathogo and @gkahiu the issue happened to me when adding new entities in the existing once. And then again when going back to them and editing them.

**Comment by pgathogo** [comment]
Cool, I'll look at it and revert.

**Comment by wondie** [comment]
This issue couldn't be reproduced for now. So I will close it for now.
