### ISSUE TITLE
Python errors 

### ISSUE THREAD

**Issue by vioannidi** [gltn/stdm#22]
1. Page 65 of the User Guide, STDM Release 1.0, v17.12.2014:
When I try to make a search in the Social Tenure Relationship View by using the Property tab, a Python error is produced: 
![property_search](https://cloud.githubusercontent.com/assets/11192516/6528458/5c4efd76-c422-11e4-9232-da063d219555.PNG)
The search by using the Person tab works fine.

2. Last line of page 89 of the User Guide, STDM Release 1.0, v17.12.2014:
When I try to Load a saved .trs file by using the STDM Report Builder, a Python error is produced:
![report_display](https://cloud.githubusercontent.com/assets/11192516/6528629/9a6b4924-c423-11e4-9832-420f31a53fe0.PNG)

**Comment by gkahiu** [comment]
Fixed in dev branch for version 1.1
