### ISSUE TITLE
Couldn't add profile prefix for entities with name similar to the profile name

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#222]
This issue happens when users create an entity with the same name or similar name. When running the Configuration wizard, the entity is created without its prefixes. The strange thing is, even if I set the prefix manually on the entity name, it still removes the prefix. 
To reproduce this issue, follow the steps below:
1. Load any profile
2. Create an entity with the same name as the profile. 
3.  Commit to database.
4. Check the configuration.stc

I got the configuration with the initial issue from the user. The user faced a stake trace due to the function that used prefix to get profile name. I will fix that issue on my side. 

[configuration(7).zip](https://github.com/gltn/stdm/files/844249/configuration.7.zip)

@pgathogo and @gkahiu the profile with issue is **settlement_profile** and the entity with issue is **settlement**.

**Comment by gkahiu** [comment]
Please fix and commit.

**Comment by wondie** [comment]
@gkahiu to which repository, to master or 1.5.0?

**Comment by wondie** [comment]
This issue is now fixed in [this commit](https://github.com/gltn/stdm/commit/7d25decdf6898e9c2ab61031a8a616a1f2981717).
