### ISSUE TITLE
Translated column data types are not being changed to a translated language

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#224]
Translated column data types are not being changed to the translated language. I see that the configuration is using the [tr](https://github.com/gltn/stdm/blob/master/data/configuration/columns.py#L58) function created within the columns.py. The[ language file](https://github.com/gltn/stdm/blob/master/i18n/stdm_fr.ts#L12) doesn't show the context of those data types. The translated texts still appear in English when switching QGIS to other languages. Could you point me on the cause and solution of the problem?

**Comment by pgathogo** [comment]
@wondie, let me review and advice.

**Comment by wondie** [comment]
This issue is fixed by changing @default content to BaseColumn.
