### ISSUE TITLE
Fix small typo in UI

### ISSUE THREAD

**Issue by 7o9** [gltn/stdm#225]
[Change "the" to "that"](https://github.com/gltn/stdm/blob/master/settings/config_file_updater.py) Approx at line 1386

**Comment by wondie** [comment]
Thank you for finding the issue. I have fixed the typo in[ this commit](https://github.com/gltn/stdm/commit/7316f13db6e43c662cbee5d3adc46c01da58e183) under the translation branch.

**Comment by 7o9** [comment]
Great, thanks.

**Comment by wondie** [comment]
You are most welcome.
