### ISSUE TITLE
 ../data/configfile_paths.py:167 

### ISSUE THREAD

**Issue by 7o9** [gltn/stdm#227]
Change title of message box from ["Configuration Exist"](https://github.com/gltn/stdm/blob/master/data/configfile_paths.py ) line 167 to "Existing Configuration"

**Comment by wondie** [comment]
Thank you for reporting the issue. This typo is fixed in [this commit](https://github.com/gltn/stdm/commit/5037769d19f521467e5d1dcb1c1eaaff6b49e6f8).
