### ISSUE TITLE
Fix UI String

### ISSUE THREAD

**Issue by 7o9** [gltn/stdm#229]
[Change "Open Street Maps" to "OpenStreetMap" (the official project name) ](https://github.com/gltn/stdm/blob/master/ui/ui_new_str.ui) line 227

[Change "Open Street Maps" to "OpenStreetMap" (the official project name) ](https://github.com/gltn/stdm/blob/master/ui/ui_property_preview.ui:189) line 189

**Comment by wondie** [comment]
Thank you for reporting the issue. This typo is fixed in[ this commit.](https://github.com/gltn/stdm/commits/stdm_translation)
