### ISSUE TITLE
Error on Loading Database Connection Properties In New Installation

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#230]
When a user installs STDM for the first time and attempts to edit the database connection settings without logging in first, then the system raises an key error exception indicating the 'Database' key cannot be found in the _setting_data_ variable [here](https://github.com/gltn/stdm/blob/master/ui/login_dlg.py#L133). 

It seems like the system is expecting a _database_ key to already exist in the settings (/registry in Windows), a check needs to be incorporated if the _database, host_ or _port_ keys are not found.

**Comment by wondie** [comment]
This issue is fixed.

**Comment by wondie** [comment]
@gkahiu were you able to test if the issue is fixed?
