### ISSUE TITLE
Use camelCase for XML Attributes

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#233]
Use camelCase for XML attributes with specific reference to [this](https://github.com/gltn/stdm/blob/master/settings/config_serializer.py#L2026) i.e. prefix_source should be **prefixSource** and leading_zero should be **leadingZero**.

**Comment by wondie** [comment]
That is noted. However, what about TYPE_INFO?

**Comment by gkahiu** [comment]
It applies as well.

John

**Comment by wondie** [comment]
Ok cool. I will work on that on version 2.0.
