### ISSUE TITLE
Couldn't add or edit columns when using STDM Arabic

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#235]
Couldn't add or edit columns when using STDM Arabic. Nothing happens when the buttons are clicked. This issue needs to be fixed before STDM 1.7 so we can deal with it later.

**Comment by pgathogo** [comment]
Does this happen with other languages?

**Comment by wondie** [comment]
No it doesn't.

**Comment by wondie** [comment]
@gkahiu do you think it is because Arabic is RTL? Is there any issue with python, Qt, PyQt, or QGIS there?

**Comment by wondie** [comment]
This issue is fixed in [this commit](https://github.com/gltn/stdm/commit/1f76daadfa54ef9950e505789fd054705d495639). The cause of the problem was translation of a variable. using `self.tr()` or `QApplication.translate()` methods. The Arabic version didn't recognize variable translation so a stack trace was raised for fewer parameters.

**Comment by gkahiu** [comment]
What about entity names? Last time we saw that Arabic characters are also not allowed.

**Comment by wondie** [comment]
Oh yea. I will allow symbols and only disallow spaces in profile, entity, column, lookup, and values names.

**Comment by wondie** [comment]
This issue is already fixed.
