### ISSUE TITLE
Error reading Foreign Key atribute form the parent table: ADMIN SPATIAL UNIT

### ISSUE THREAD

**Issue by SolomonN** [gltn/stdm#238]
My code"
prof = current_profile()

ent = prof.entity("Terra")
print "Entity columns "
cols = ent.columns.values()
for c in cols:
    print 'Column Name  ' + c.name +' '+ ' Type  ' +c.TYPE_INFO
    
lookup_col = ent.columns["comuna"]
print lookup_col.parent.name

print entity_attr_to_id(lookup_col.parent, "name", "Nairobi")

result:
Etity columns 
Column Name  id  Type  SERIAL
Column Name  identificador  Type  VARCHAR
Column Name  geometria  Type  GEOMETRY
Column Name  construcao  Type  BOOL
Column Name  data_da_construcao  Type  DATE
Column Name  confrontacoes_norte_tipo  Type  LOOKUP
Column Name  confrontacoes_norte_nome  Type  VARCHAR
Column Name  confrontacoes_sul_tipo  Type  LOOKUP
Column Name  confrontacoes_sul_nome  Type  VARCHAR
Column Name  confrontacoes_oeste_tipo  Type  LOOKUP
Column Name  confrontacoes_oeste_nome  Type  VARCHAR
Column Name  confrontacoes_este_tipo  Type  LOOKUP
Column Name  confrontacoes_este_nome  Type  VARCHAR
Column Name  licenca_ampliacao  Type  BOOL
Column Name  licenca_construcao  Type  BOOL
Column Name  licenca_arrematacao  Type  BOOL
Column Name  linceca_construcao_provincia  Type  BOOL
Column Name  lincenca_demolicao  Type  BOOL
Column Name  licenca_reabilitacao  Type  BOOL
Column Name  licenca_vedacao  Type  BOOL
Column Name  uso  Type  LOOKUP
Column Name  provincia  Type  ADMIN_SPATIAL_UNIT
Column Name  municipio  Type  ADMIN_SPATIAL_UNIT
Column Name  comuna  Type  ADMIN_SPATIAL_UNIT
Column Name  bairro  Type  VARCHAR
Column Name  tamanho  Type  DOUBLE
admin_spatial_unit_set
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "c:/users/solomon/appdata/local/temp/tmpswu4xz.py", line 16, in <module>
    print entity_attr_to_id(lookup_col.parent, "name", "Nairobi")
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\utils\util.py", line 744, in entity_attr_to_id
    doc_type_model = entity_model(entity)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\data\configuration\__init__.py", line 72, in entity_model
    children = [c.name for c in entity.children()]
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\data\configuration\entity.py", line 358, in children
    entity_relations = self.profile.parent_relations(self)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\data\configuration\profile.py", line 255, in parent_relations
    raise TypeError(self.tr('Entity object type expected.'))
TypeError: Entity object type expected.

**Comment by wondie** [comment]
This issue also happen to me since the removal of the help file. I don't
know why it started happening. The work around is not to use plugin
reloader. John can comment on this.

**Comment by gkahiu** [comment]
When is this raised? When printing the TYPE_INFO? Not clear to me
