### ISSUE TITLE
Stack trace when accessing `Options` menu.

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#242]
Hello Guys,

Am getting the following stack trace when trying to access the `Options` menu.

```
An error has occurred while executing Python code: 

TypeError: QLineEdit.setText(QString): argument 1 has unexpected type 'int' 
Traceback (most recent call last):
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\plugin.py", line 1264, in on_sys_options
    opt_dlg = OptionsDialog(self.iface)
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\options_base.py", line 120, in __init__
    self.init_gui()
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\options_base.py", line 136, in init_gui
    self._load_db_conn_properties()
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\ui\options_base.py", line 167, in _load_db_conn_properties
    self.txtPort.setText(db_conn.Port)
TypeError: QLineEdit.setText(QString): argument 1 has unexpected type 'int'

```
Regards,

Paul

**Comment by gkahiu** [comment]
Hi,

That is a strange error because the port is saved as a _string_ in the settings (registry in Windows), see screenshot below:
![image](https://user-images.githubusercontent.com/3840267/28270127-07ab9272-6b0d-11e7-9895-cd05b2410a86.png)

Could you check whether it is saved as an _int_ data type in your settings? If it is a string then it means there is somewhere it is being converted to an _int_ while retrieving it; if not, then it means that there is a revision in a piece of code that updates it by saving it as an _int_.

**Comment by pgathogo** [comment]
Hi,
On my machine the port is saved as an _int_, and I thought that should be the norm.

**Comment by gkahiu** [comment]
Ideally it should be int but this will be changed in version 2.0, for now it is not really a blocker so I would give it low priority.

Could you delete the settings in the registry and try to log in again, re-enter the database connection properties then check the registry to see the type that has been created?

**Comment by pgathogo** [comment]
I deleted my old _int_ port registry entry, re-run the application and the issue seems resolved. However,  does it mean that the current STDM users with a _string_ version of the port number will experience the same problem?

**Comment by gkahiu** [comment]
It has always been a string, not sure why in your setup it ended up being
an int. I also have not experienced this issue before even in the most
recent training that we conducted yesterday in Kathmandu.

**Comment by gkahiu** [comment]
@pgathogo is this issue still valid or we close it?

**Comment by pgathogo** [comment]
@gkahiu, not valid, I will close it.
