### ISSUE TITLE
Stack trace when switching profile

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#243]
Guys,

Am getting the following stack trace on the latest master branch when I attempt to switch a profile at the combobox  on the main STDM toolbar.

```
AttributeError: 'NoneType' object has no attribute 'social_tenure' 
Traceback (most recent call last):
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\plugin.py", line 1366, in reload_plugin
    self.loadModules()
  File "C:/Users/Administrator/.qgis2/python/plugins\stdm\plugin.py", line 898, in loadModules
    social_tenure = self.current_profile.social_tenure
AttributeError: 'NoneType' object has no attribute 'social_tenure'

```
Regards,

Paul

**Comment by gkahiu** [comment]
Which version? Master or 1.6?

**Comment by pgathogo** [comment]
@gkahiu , latest master.

**Comment by gkahiu** [comment]
@wondie please have a look at this issue.

**Comment by wondie** [comment]
This issue is now fixed in [this commit](https://github.com/gltn/stdm/issues/243). Please test it.

**Comment by wondie** [comment]
Is this issue fixed for you @pgathogo ?

**Comment by pgathogo** [comment]
This is issues is fixed.
