### ISSUE TITLE
Unexpected error when saving a new STR

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#245]
Hello guys,
On STDM 1.6.3, I got the following "unexpected error" when I was trying to save a new STR.

![saving_str](https://user-images.githubusercontent.com/155431/28996341-5c755a6e-7a07-11e7-960f-51195b7d78a8.PNG)

Regards.

**Comment by wondie** [comment]
Could you comment out the try: expect block so that we get a full stack trace?

**Comment by wondie** [comment]
Are you still getting issue?

**Comment by pgathogo** [comment]
This issue is fixed.
