### ISSUE TITLE
Data export error

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#246]
Dear guys,
On STDM 1.6.3, I got the following "Data export error" when I attempted to export an entity to a CSV file.

![exporting_data](https://user-images.githubusercontent.com/155431/28996386-4262395c-7a08-11e7-8360-12e43eee44bf.PNG)

Regards.

**Comment by wondie** [comment]
I also expereinced this issue in the Kampala training. This error is fixed during the training and incorporate in tranees' STDM, [ in master branch](https://github.com/gltn/stdm/commit/c54bd1f0333f40a94755328c86b187b4faa1ffa5) and if we release another patch release, I have created [rel-1_6_4 incorporating the fix](https://github.com/gltn/stdm/commit/d1ea728ba8e425e3f5c9c82067fe27165259a097).

**Comment by pgathogo** [comment]
Issue is now fixed. Thank you.
