### ISSUE TITLE
Invalid input syntax when importing data

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#247]
Dear guys,
On STDM 1.6.3, I got the following "Data error" when importing sample data to an existing entity. But when I did a value translation on the the Gender lookup column, the error went away and I was able to import the data.

![importing_data](https://user-images.githubusercontent.com/155431/28996472-e81661b0-7a09-11e7-99ba-afce9fef4616.PNG)

Regards.

**Comment by wondie** [comment]
This is because you have to use the lookup translator when importing in lookup columns as it is a foreign key column.

**Comment by wondie** [comment]
@pgathogo is this issue fixed?

**Comment by pgathogo** [comment]
I was made to understand that the whole **Import/Export** module is to be redesigned from scratch with STDM 2.0 and all these cryptic messages should disappear. With that, I will close and defer this issue to STDM version 2.0
