### ISSUE TITLE
Ability to customize STDM data labels by adding html and extra text

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#252]
Requirements:
1.	Basic knowledge of HTML, please refer this help and other resources online. 
2.	Basic knowledge of STDM Documents Designer.

Users can now style the data label by enabling HTML using the checkbox, **Render as HTML option** as located in the **item properties** of Documents Designer as shown in the image below. 
![image](https://user-images.githubusercontent.com/9709624/29117404-b876e34e-7d06-11e7-98fb-59ba62d3c85f.png)

You need to add html style to modify the appearance of the data label. This enables users to add styles such as wrapping, color, etc.
As shown below. 

This is achieved after selecting the data source field of the data label then by wrapping the data label in html `p` (paragraph) tag.   
```
<p style="color:blue;width:30px;height:100px;"> [in_structure_vw_social_tenure_relationship.structure_ownership_type]</p>
```
The following code modifies the appearance of the data label in the following way. 

`style="color:blue;width:30px;height:100px;"` is the style affecting the appearance. 
`Color: blue` changes the color of the label to blue.
`Width:30px` – restricts the width of the data label to 30 pixels only. The width of the data label box should be at least same as the width or larger. 
`Height:100px` - restricts the height of the data label to 100 pixels only. The width of the data label box should be at least same as the width or larger as shown below. 
![image](https://user-images.githubusercontent.com/9709624/29117965-e6fa54b0-7d08-11e7-9f56-216d9dd25572.png)
Users can add any height, width, color using rgb or hex color codes and any other html styles.

Users can also add text that acts as a label to the data label by adding in front or after the data label. 
This reduces the number of items added to the template, which makes it easier to resize, move items, etc. The image below shows example implementation.
![image](https://user-images.githubusercontent.com/9709624/29118008-11c8c244-7d09-11e7-8390-85449c7e7754.png)
The result below shows the effect of the HTML and added text in the data label.

![image](https://user-images.githubusercontent.com/9709624/29118304-1115222e-7d0a-11e7-800d-0ed58b1ed92a.png)

For Attribute tables in Designer, it is possible to use warp text feature and other styling functionalities since STDM version 1.4 as shown in the image below. 

![image](https://user-images.githubusercontent.com/9709624/29118576-3671ba90-7d0b-11e7-8668-a5d114f7ab1f.png)
 
**Important Notes:** 

- Make sure not to remove or modify the data label part starting with ‘[‘ and ending ‘]’ manually. Use the STDM Data Source panel instead to change data source field. 
- If Render as HTML checkbox is uncheck all the html code will appear as text. 

**Target version:**
STDM 1.7 - but already incorporated in master.

**Comment by gkahiu** [comment]
Great @wondie I hope there will be accompanying documentation in the user manual.

**Comment by wondie** [comment]
Definitely, there will be, when 1.7 is release.
