### ISSUE TITLE
List object has no attribute column

### ISSUE THREAD

**Issue by SolomonN** [gltn/stdm#253]
I l found this error when  I log in after updating geoodk branch with current master

  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\plugin.py", line 322, in login
    self.iface.mainWindow()
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\plugin.py", line 716, in load_configuration_from_file
    result = self.load_configuration_to_serializer()
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\plugin.py", line 571, in load_configuration_to_serializer
    self.config_serializer.load()
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 161, in load
    self.read_xml(config_doc)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 297, in read_xml
    self._load_config_items(doc_element)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 308, in _load_config_items
    self.config)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 476, in read_xml
    entity_relation_elements)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\settings\config_serializer.py", line 604, in read_xml
    sp_units
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\data\configuration\profile.py", line 184, in set_social_tenure_attr
    setattr(self.social_tenure, attr, val)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\data\configuration\social_tenure.py", line 867, in spatial_unit
    sp_unit_id = self._entity_id_column(spatial_unit_entity)
  File "C:/Users/SOLOMON/.qgis2/python/plugins\stdm\data\configuration\social_tenure.py", line 925, in _entity_id_column
    return entity.column('id')
AttributeError: 'list' object has no attribute 'column'

**Comment by gkahiu** [comment]
Hi Solomon,

That is a strange error because it is raised by a block of code that has since been deprecated (see ref [here](https://github.com/gltn/stdm/blob/master/data/configuration/social_tenure.py#L856)). The most likely source of the error is the profile code which might not have necessarily updated when you were pulling from the repository; to confirm, could you please browse to _stdm/data/configuration/profile.py_ and locate the following block of code:
```
    def set_social_tenure_attr(self, entity_type, val):
        """
        Sets the specified property of the SocialTenure object.
        :param attr: Enumeration type of an social tenure relationship entity.
        :type attr: int
        :param value: Attribute value. A string or object can be passed; if
        it is the former then the corresponding entity will be used if it
        exists in the collection.
        :type value: str
        """
        if entity_type == SocialTenure.PARTY:
            # Renamed from 'party' in v1.5
            attr = 'parties'

        elif entity_type == SocialTenure.SPATIAL_UNIT:
```
In your set up, could you please indicate what comes immediately below `elif entity_type == SocialTenure.SPATIAL_UNIT`?

**Comment by SolomonN** [comment]
Dear John,Thanks for your response.This is the result in that referred piece of code:if entity_type == SocialTenure.PARTY:
    # Renamed from 'party' in v1.5
    attr = 'parties'

elif entity_type == SocialTenure.SPATIAL_UNIT:
    attr = 'spatial_unit'

elif entity_type == SocialTenure.SOCIAL_TENURE_TYPE:
    attr = 'tenure_type_collection'

elif entity_type == SocialTenure.START_DATE:
    attr = 'start_date'

elif entity_type == SocialTenure.END_DATE:
    attr = 'end_date'

else:
    LOGGER.debug('%s is an invalid enumeration for social tenure '
                 'entity type.', str(entity_type))

    return
 Kind Regards,
Solomon Njogu.Land Management Land Tenure - TUM, Germany.Mobile +254 724 291046, +4915218657520 

    On Thursday, August 10, 2017 2:17 PM, Kahiu <notifications@github.com> wrote:
 

 Hi Solomon,That is a strange error because it is raised by a block of code that has since been deprecated (see ref here). The most likely source of the error is the profile code which might not have necessarily updated when you were pulling from the repository; to confirm, could you please browse to stdm/data/configuration/profile.py and locate the following block of code:    def set_social_tenure_attr(self, entity_type, val):
        """
        Sets the specified property of the SocialTenure object.
        :param attr: Enumeration type of an social tenure relationship entity.
        :type attr: int
        :param value: Attribute value. A string or object can be passed; if
        it is the former then the corresponding entity will be used if it
        exists in the collection.
        :type value: str
        """
        if entity_type == SocialTenure.PARTY:
            # Renamed from 'party' in v1.5
            attr = 'parties'

        elif entity_type == SocialTenure.SPATIAL_UNIT:
In your set up, could you please indicate what comes immediately below elif entity_type == SocialTenure.SPATIAL_UNIT?—

**Comment by gkahiu** [comment]
As I thought, your _profile_ module is not updated, it should read:
```
elif entity_type == SocialTenure.SPATIAL_UNIT:
    attr = 'spatial_units'
```
Where spatial units should be plural as the code in master now support multiple spatial units participating in a social tenure relationship context, see reference [here](https://github.com/gltn/stdm/blob/master/data/configuration/profile.py#L158)

That said, you might need to sync all your changes with those in master.

Let me know.

**Comment by gkahiu** [comment]
@SolomonN is this issue resolved we close it?
