### ISSUE TITLE
Integrate GPS Feature Import to Entity Browser

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#263]
The Spatial Entity Browser has no option to add a record directly from within the Entity Browser. This is now possible if the user uses GPX file. The placement makes it more sensible and easier to add a record for users than adding a layer -> selecting the layer --> clicking GPS Feature Import button. 
![image](https://user-images.githubusercontent.com/9709624/31862141-11240542-b742-11e7-901c-a2b41d19ad71.png)

However, if no GPX file is specified, adding a record is not possible. The following error message will be shown that also suggests a solution. 
 ![image](https://user-images.githubusercontent.com/9709624/31862142-1c026e90-b742-11e7-8b6a-db97b01b51d7.png)

Editing a record was already possible in the previous version but with no ability to edit geometry. It was only possible using the QGIS Mapcanvas, which is a bit more technical. If for instance a user imported geometry using the GPS Feature Import tool and there was a mistake in selecting a feature, users can now just replace the geometry by editing and specifying the GPX file and feature. 

Thus, if users are using GPS device to collect geometry of a record, they can benefit from this new feature. 

The last bit of the change is done in [this commit](https://github.com/gltn/stdm/commit/ec584d373b55959d26bc3c75d3a8bcb50be9b5ee).

**Comment by gkahiu** [comment]
@wondie thanks for this addition, it improves the user experience in adding new features. In future (i.e. version 2.0), I would suggest we not only consider GPX files but also other options such as direct digitization. That means the design of the code should be modular to allow extensibility. 

Similarly, and for consistency purposes, please consider also whether editing (from the entity browser) should also include spatial editing of the feature.

**Comment by wondie** [comment]
You are welcome and thanks for the feedback and suggestion. It will be nice addition if we also include the digitization and editing features from within the entity browser. I think it is doable for 2.0. 

In STDM 2.0, I think we can also remove the GPS Feature Import button from Spatial Unit Manager.

**Comment by SolomonN** [comment]
Dear Wondie, Thanks for this addition and I have tested it briefly. However, when you are editing the database entry, it does not pick the existing gpx feature but requires you to upload it again, otherwise you will not be able to save the edits.Kind Regards,
Solomon Njogu.Land Management Land Tenure - TUM, Germany.Mobile +254 724 291046, +4915218657520 

    On Monday, October 23, 2017, 10:11:57 AM GMT+3, Wondimagegn Tesfaye <notifications@github.com> wrote:  
 
 
You are welcome and thanks for the feedback and suggestion. It will be nice addition if we also include the digitization and editing features from within the entity browser. I think it is doable for 2.0.

In STDM 2.0, I think we can also remove the GPS Feature Import button from Spatial Unit Manager.

**Comment by wondie** [comment]
The reason is because it requires storing the reference of the uploaded gpx files to the database or somewhere else which requires changes in the configuration. Moreover, if the user have shifted the file, or used digitization, this will be useless. So the user needs to keep reference of the gps file name in the questionnaire and re-upload it again if he/she wants to update the geometry.

When I tried to edit only text without the Geometry, it allowed me to save it. Could you share me the steps so that I reproduce your issue.

**Comment by wondie** [comment]
@SolomonN I have found the issue. The reason I was not able to reproduce it earlier was I tested it using the stdm_geoodk branch. I have fixed the issue in[ this commit](https://github.com/gltn/stdm/commit/0b241211019d55fc0314aea64632a4435384bdcb). Please test and report if the issue is fixed.
