### ISSUE TITLE
Encoding issues in non-English languages of Mobile tools

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#264]
The issue affects both the mobile form export and import data modules.

**Comment by SolomonN** [comment]
I will test this and fix

**Comment by SolomonN** [comment]
Dear Wondie, Is there an English translation for the lookup values.

**Comment by wondie** [comment]
Dear Solomon, yes it is available but that is not used in the field.

**Comment by wondie** [comment]
This issue is an encoding issue. If you make the python code recognize unicode, it will be great. I have been fixing several similar issues. 

These are some of the methods used to covert ascii code to non-ascii. 
string.encode("utf-8")
string.decode("utf-8")
unicode(string)
u"the string"

**Comment by SolomonN** [comment]
Dear Wondie,
I have made some changes to support encoding but this is only a temporary fix
Please check again and let me know your findings.

**Comment by wondie** [comment]
Dear Solomon, 

I tested today and the problem still exists. Please use the configuration.stc I shared you last time to test it too.

**Comment by wondie** [comment]
The issue is now fixed in [this commit](https://github.com/gltn/stdm/commit/68260385594f6fc2a57aa62a5aa98e312d346208).
