### ISSUE TITLE
When editing a column data type display_name changes to TYPE_INFO 

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#269]
When editing a column data type display_name (eg. Whole number) changes to TYPE_INFO (eg. Int) that is confusing. 

![image](https://user-images.githubusercontent.com/9709624/33002751-37e4f61e-cdc7-11e7-8101-3e9d27eec8a4.png)

**Comment by pgathogo** [comment]
Issues is now fixed

**Comment by wondie** [comment]
This issue is now fixed!
