### ISSUE TITLE
Moving the attribute table of designer makes QGIS to crash

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#271]
The issue happens when a moving the attribute table. It is intermittent problem but sometimes repeated. 
In a training a user experienced three crash in three attempts. When I advised them not to move it immediately and wait a bit to move it, it worked. I hope, this workaround could give an idea to fix the issue.

**Comment by pgathogo** [comment]
Did this happen on your machine? Am totally unable to reproduce it. 
I'll keep on trying see if I can recreate the issue.

**Comment by wondie** [comment]
For me it happened once in Nepal training. But another trainee faced it 3 times in a row.

**Comment by wondie** [comment]
Oh I was able to reproduce it correctly! Below is the step. 
1. Add an STDM layer.
2. Open designer
3. Add the attribute table without selecting a data source
4. Move the attribute table
5. QGIS crashes

**Comment by gkahiu** [comment]
Dear Paul,

This also happened during the Zambia training in August.

Regards,

John

**Comment by gkahiu** [comment]
This issue seems to be QGIS minor-version specific. I cannot reproduce it in 2.18.3. Could you all check whether its still there in 2.18.14?

**Comment by wondie** [comment]
I have checked on 2.18.14 and the crash still happens.

**Comment by wondie** [comment]
If it is hard to fix, I guess a check can be done requiring users to select data source. This can be done for instance by disabling data driven items until the data source is selected.

**Comment by pgathogo** [comment]
@wondie , I followed the steps above, but everything is working OK. Please confirm your QGIS version.

**Comment by wondie** [comment]
It happens in both  2.18.3 and  2.18.14. I just reproduced it again.

**Comment by pgathogo** [comment]
This issue is now fixed.

**Comment by wondie** [comment]
I tested that this issue is now fixed!
