### ISSUE TITLE
Not able to add or delete columns in Custom Tenure Attributes entity once tables are created

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#277]
In other entities users are able to add columns even though it is not possible to edit them once the columns are created in the configuration. However, for Custom Tenure Attributes entity once the table is created, everything is disabled which makes it impossible delete or add columns. 
![image](https://user-images.githubusercontent.com/9709624/33024477-3d1c78dc-ce1c-11e7-8108-2a0fbf3bc85a.png)

**Comment by pgathogo** [comment]
I have enabled editing of columns for attributes entities, however, since I didn't implement the original functionality for custom attributes, am not sure what will be the impact of adding/editing or deleting columns for already saved custom attribute tables.

**Comment by wondie** [comment]
Considering that custom tenure attr entity is just a normal entity, I don't see any problem of adding or removing columns. However, @gkahiu can advice better as you indicated.

**Comment by wondie** [comment]
This issue is now fixed.
