### ISSUE TITLE
Saving a draft profile is disabled until back and next buttons are clicked

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#280]
The "Save draft" menu is mostly disabled even if there are changes to the configuration. Is it possible to either detect the changes or always enable the button for users to save it at the time of their liking? 

@pgathogo editing the order through drag and drop also needs to be saved but the save draft button is not enabled when order changes.

**Comment by pgathogo** [comment]
Resolved. "Save draft" is now enabled by default.

**Comment by wondie** [comment]
This issue is now fixed!
