### ISSUE TITLE
Column options are enabled even if the column is created in the database in the wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#284]
Column options such as mandatory, unique, indexed, etc are enabled even if the column is created in the database in the wizard.

**Comment by pgathogo** [comment]
@wondie , this is the correct behavior, unless the requirements have changed.

**Comment by wondie** [comment]
@pgathogo I though all options especially database options were supposed to be disable. This is because, once a column is created, those options are not working. 
This is the SQL of person table. 
![image](https://user-images.githubusercontent.com/9709624/33516059-09e9bab4-d77d-11e7-8a29-e5a1e6489abc.png)
And this is the option for first name which is part of the person table. 
![image](https://user-images.githubusercontent.com/9709624/33516066-275cb696-d77d-11e7-9f9c-5c5d912921e2.png)
I checked on the above options after I created the column.

**Comment by pgathogo** [comment]
This issue has been resolved. All options are now disabled once the column has been saved on the database.

**Comment by wondie** [comment]
This is good. Could you please leave Searchable from being disabled as it is not database dependent and users should be able to enable and disable anytime.

**Comment by pgathogo** [comment]
This issue is fixed.

**Comment by wondie** [comment]
Yes it is fixed.
