### ISSUE TITLE
Profile Editor Does Not Allow Non-ASCII Characters

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#289]
I tried to specify a new profile name in Arabic and got the following exception:

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISLA~1.3)F/apps/qgis/./python/plugins\stdm\ui\wizard\profile_editor.py", line 92, in validate_text
    format(last_character)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u062c' in position 0: ordinal not in range(128)
```

The `validate_text` function seems to be the one raising the exception. Use utf-8 string functions.

**Comment by wondie** [comment]
@gkahiu please note that, to create profile that uses Arabic words, you need to switch to non-English profiles where ascii is not used. In addition, we never tested stdm with non-ascii database objects. Naming the profile in Arabic will give as Arabic prefix and many more uknown encoding errors could come as it was not tested.

**Comment by gkahiu** [comment]
Am testing that now, am fixing a couple of issues, mostly related to string
formatting. I’ll try to get to the end.

**Comment by wondie** [comment]
That is great!

**Comment by gkahiu** [comment]
Hit a dead end. Python 2 does not allow non ASCII object identifiers hence model classes for database operations containing non ASCII characters are invalid. A workaround is to add a label attribute for an entity, which could then be used for UI display purposes.
