### ISSUE TITLE
Remove MessageBox When Adding a New Column in Form Designer

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#29]
When clicking to add a new column for a table, a message box showing something like an empty list pops up. I believe this is remnant code that should be cleaned up.

**Comment by SolomonN** [comment]
The issue is Fixed. Kind Regards,
Solomon.Mobile +254 724 291046 


     On Saturday, June 27, 2015 3:13 PM, Kahiu <notifications@github.com> wrote:
   

 When clicking to add a new column for a table, a message box showing something like an empty list pops up. I believe this is remnant code that should be cleaned up.—
