### ISSUE TITLE
Misplaced columns in STR editor 

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#290]
Entity columns on the Tenure Information browser of STR editor are misplaced. Please refer to image below.
![column misplacement str](https://user-images.githubusercontent.com/155431/33794559-863b29e2-dcdf-11e7-8038-bf77c3f8318c.jpg)

**Comment by wondie** [comment]
@pgathogo this issue will not affect the data saved to the database. Could you send me the database backup and the configuration to me.

**Comment by pgathogo** [comment]
It does not, but users didn't know that its just a display issue. Can it be resolved to display columns correctly?

**Comment by wondie** [comment]
I know, I said I will fix but you need to send me the database backup if I already have the configuration.

**Comment by wondie** [comment]
@pgathogo this issue is fixed. Please test.

**Comment by pgathogo** [comment]
This issue is fixed.
