### ISSUE TITLE
Related Entity display columns ignores Numeric data type.

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#291]
If you select a column that has a numeric data type as a display column for Related Entity that entity column returns nothing during selection in a form.

**Comment by wondie** [comment]
This is noted. It will be fixed. Waiting for your configuration and database backup.

**Comment by pgathogo** [comment]
@wondie , which configuration and database?

**Comment by wondie** [comment]
What you are using.

**Comment by pgathogo** [comment]
Is the same one I sent you on Wednesday.

**Comment by wondie** [comment]
Could you send me the database backup you have.

**Comment by wondie** [comment]
The issue is now fixed.

**Comment by pgathogo** [comment]
This is fixed.
