### ISSUE TITLE
How to add multiple related entity in STDM GeoODK?

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#297]
If there are multipple records linked to another entity from another entity, how do we add them in GeoODK.

**Comment by SolomonN** [comment]
Could you give an example on this to be more clear.

**Comment by wondie** [comment]
For instance, a household is the party entity and the household contains household members. How could I add multiple household members and make sure they are linked to the household being entered?

**Comment by SolomonN** [comment]
If they are separate files,  it will be difficult without matching key in db.  However, there are some work around that could be implemented.
