### ISSUE TITLE
PersonDocumentGenerator ImportError

### ISSUE THREAD

**Issue by eomwandho** [gltn/stdm#30]
I'm getting error while loading stdm plugin see gist below

https://gist.github.com/eomwandho/29336b98838cce1f9141

**Comment by gkahiu** [comment]
Check your merge as* PersonDocumentGenerator* has been removed, please
check here: https://github.com/gltn/stdm/blob/master/stdm.py#L31

**Comment by eomwandho** [comment]
Let me check I'm pulling changes again
