### ISSUE TITLE
Once the lookup value is wrong, it won't change

### ISSUE THREAD

**Issue by meshuman** [gltn/stdm#301]
Once the lookup value is changed like lookups -> value with wrong character length i.e. more than 5 characters, it gives error after configuring. So, when coming back to edit and save, it won't update. 
![bug-lookup](https://user-images.githubusercontent.com/4783005/37251689-e3762c10-253c-11e8-95ea-92d574a363d9.PNG)

**Comment by gkahiu** [comment]
Related to issues #299 and #300 . These have been fixed in master, please pull and test.
