### ISSUE TITLE
Editing lookup tables moves its index to bottom but not the actual value

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#303]
When I edited a lookup table, it messed up the index by moving its index to the bottom but not the item text. This resulted in display of item which is not selected as shown below. 

![image](https://user-images.githubusercontent.com/9709624/37255245-ba0f35a8-2571-11e8-8660-968adbc78b57.png)

**Comment by pgathogo** [comment]
This issue is now fixed. Disabled editing of lookups that already exists in database.
