### ISSUE TITLE
Several Mobile Data Import Errors

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#310]
Importing from mobile form has the following issues:

1. When a Percent column is empty, there is a stack trace: invalid input syntax for integer: ""
2. When importing administrative unit columns has no values the stack trace: invalid input syntax for integer: ""
3. When importing administrative unit columns has value with wrong code or name the stack trace: invalid input syntax for integer: "[the wrong value]" is shown. 
4. When importing DATETIME or DATE  has no values the stack trace: invalid input syntax for timestamp or date: ""
5. The administrative unit column is converted to text box and the user is required to have a matching code or name. Otherwise, it will show an error. The string length is also not enough to determine if it is code or name. We need to have a proper way of [handling administrative unit](https://github.com/gltn/stdm/blob/master/geoodk/importer/entity_importer.py#L415). 
6. Column constraints (options) are not enforced when importing as pre-validation is not done for unique constraints. 
7. If importing succeeds in some entities, only that entity is imported and when the user try again, duplicate import happens. 
8. The coordinate system that is set by default needs to come from the entity geometry column than from the map canvas. If it doesn't match, reprojecting the mobile data could be a better. 

My suggestion is, the following:
1. All the columns should be translated properly. 
2. All the columns constraints should be enforced both[ in the form](https://github.com/gltn/stdm/issues/306) and when importing. 
3. Duplicate importing needs to be prevented using db transactions and rollback in case of error.

**Comment by SolomonN** [comment]
Fixed

**Comment by SolomonN** [comment]
Update on Administrative unit still pending
