### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Tharcille** [gltn/stdm#318]
I have  successifully installed QGIS for STDM but the problem happened while trying to open it. Desktop shortcut is not opening as well as the software. the only way to open it is through batch process.

**Comment by pgathogo** [comment]
Hi, what version of Windows are you running?

**Comment by Tharcille** [comment]
Hello,I have installed STDM of 64 bits. my laptop has windows 10 with 64 bits.
Regards,



...DUKUZEMARIYA TharcilleAssistant LecturerLand survey departmentINES-RUHENGERIMobile:+250785105598 

    Le vendredi 11 mai 2018 à 09:30:51 UTC+3, pgathogo <notifications@github.com> a écrit :  
 
 
Hi, what version of Windows are you running?

**Comment by gkahiu** [comment]
Related to issue #337

**Comment by Tharcille** [comment]
Hi, I am running windows 10


...DUKUZEMARIYA TharcilleAssistant LecturerLand survey departmentINES-RUHENGERIMobile:+250785105598 

    Le vendredi 11 mai 2018 à 09:30:51 UTC+3, pgathogo <notifications@github.com> a écrit :  
 
 
Hi, what version of Windows are you running?
