### ISSUE TITLE
UI/UX - More information required 

### ISSUE THREAD

**Issue by MelHarrington** [gltn/stdm#323]
In "Person Editor" the information (displayed under the icon) is not helpful.

For example, the "First name of person” should say “first name of the person you are interviewing”.

![image](https://user-images.githubusercontent.com/39157881/39868753-9905f858-5463-11e8-9666-75a458f28267.png)

**Comment by pgathogo** [comment]
@MelHarrington, thanks for your suggesting, however, that information you see under the  icon (which we call 'User Tip') is totally customizable by the user, you can change it to your preferred text. Please refer to this  [link](https://www.stdm.gltn.net/docs/1_7/#t=Creating_Columns.htm) to see how to edit Column User Tip.
