### ISSUE TITLE
UX Design Issue - Enter instead of Mouse Clicks

### ISSUE THREAD

**Issue by CBizzle02** [gltn/stdm#324]
View social tenure relationship ‘search by’ function needs the option to hit “enter” to search instead of having to mouse click “search” 
![ui_ux search functionality](https://user-images.githubusercontent.com/39157891/39869128-80c3910e-54b0-11e8-9625-461d2e4765fe.png)

**Comment by pgathogo** [comment]
@CBizzle02 , This is well noted. We shall included it on our next minor release. 

Thanks
