### ISSUE TITLE
UX Design Issue - Terminology consistency confusing (1)

### ISSUE THREAD

**Issue by CBizzle02** [gltn/stdm#328]
When you set up the Administrative Units and then go to capture the person's details, the words
Residence Area is used instead of Administrative Unit.   They are the same thing so they should be named the same.
![1-_manage_administrative_v _residence_area](https://user-images.githubusercontent.com/39157891/39869420-88782f1c-54b1-11e8-819e-ab45ea055baf.png)

**Comment by pgathogo** [comment]
@CBizzle02 , **Manage Administrative Units**  is the name of the module responsible for creating administrative hierarchical data used in a column of an entity. In your example above, **Residence Area** is a column in the entity **Person** whose values are picked from the data created in the **Manage Administrative Units** module.
For more, please refer to this [link](https://www.stdm.gltn.net/docs/1_7/#t=managingadministrativeunit.htm) on how to  manage administrative units in STDM.
