### ISSUE TITLE
UX Design Suggestion - Manage Administration Levels (12)

### ISSUE THREAD

**Issue by CBizzle02** [gltn/stdm#330]
The tree in this window should automatically expand out the top level administrative level when a new lower level administrative level is added.
![12 add_new_admin_unit improvement](https://user-images.githubusercontent.com/39157891/39869920-934f34ec-54b3-11e8-892e-4e5a2970571e.png)

**Comment by wondie** [comment]
Thanks for the suggestion. This feature is already applied in recent STDM
master. When we release a new version, you will get the update.
