### ISSUE TITLE
Installation Problem: Shortcut not working

### ISSUE THREAD

**Issue by kwesikuffa** [gltn/stdm#337]
I have a problem installing the STDM-1.7.4 Final-x86_64 version.
It installs successfully, but upon double clicking, nothing changes.

Below is the attached specifications of the computer.
Windows 10 Home Premium x64

![installation_problem](https://user-images.githubusercontent.com/9099704/39873448-a8941fb0-5473-11e8-80de-ac32e81eba2b.JPG)

**Comment by pgathogo** [comment]
@kwesikuffa , this is well noted, we are currently experiencing an issue with shortcut not working in Windows 10, we are looking at it, once a solution is found we shall update you ASAP.
