### ISSUE TITLE
Disable Non-ASCII Characters for Entity and Column Names

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#345]
Database foreign keys, generated from STDM entity relation objects, containing non-ASCII characters are causing errors at the database level when the schema is being updated. I suggest input of non-ASCII characters be disabled when specifying entity and columns names respectively. The display in the user-interface can always be adapted using the **Label** field.

Also, [this](https://github.com/gltn/stdm/blob/master/ui/wizard/column_editor.py#L207) check should be locale-independent as this condition is skipped when the locale is 'fr' thereby allowing non-ASCII characters to be entered.

**Comment by pgathogo** [comment]
This issue is now fixed.

**Comment by gkahiu** [comment]
Great thanks. I will close the issue and re-open if I encounter any issues

**Comment by wondie** [comment]
Similar fix needs to be done for in create_lookup.py, copy_editor.py, profile_editor.py. But I don't think we need to disable it in create_lookup_value.py
