### ISSUE TITLE
How to lock the produced map template on a specific scale?

### ISSUE THREAD

**Issue by vutegha** [gltn/stdm#348]
Hi @gkahiu .

I designed a template linked to a specific personalized view. 
Everything works well but the issue comes when I generate the map from the given template.
I can set a scale to `1:1000` but the map comes out with something like `1:141319749`. 

In my specific case, the scale is predefined and it is standard.
Note that I am using the master-stdm version downloaded few days ago. 

Thoughts?

**Comment by gkahiu** [comment]
@wondie kindly assist. Might be similar with the Uganda context.

**Comment by wondie** [comment]
@vutegha this feature is not there in STDM master. However, there is an implementation of fixed scale on STDM customization to Nepal. If you are interested, you can get it from [here](https://github.com/gltn/stdm/tree/stdm_nepal).

**Comment by gkahiu** [comment]
@wondie , is there a specific code snippet for fixing the scale to help him narrow down?

**Comment by wondie** [comment]
Yes. Below are the links showing where it is implemented. 
https://github.com/gltn/stdm/blob/stdm_nepal/ui/composer/composer_spcolumn_styler.py#L164
https://github.com/gltn/stdm/blob/stdm_nepal/composer/spatial_fields_config.py#L128
https://github.com/gltn/stdm/blob/stdm_nepal/composer/document_generator.py#L393

**Comment by vutegha** [comment]
Thanks @wondie.
I will try implement it. I will revert back to you if necessary.

**Comment by wondie** [comment]
@vutegha sounds cool.

**Comment by wondie** [comment]
Also please note that the UI file [here ](https://github.com/gltn/stdm/blob/stdm_nepal/ui/composer/ui_composer_spcolumn_styler.ui) is modified to received both fixed scale and zoom level.
