### ISSUE TITLE
Identifier exceeds maximum length error

### ISSUE THREAD

**Issue by nyalldawson** [gltn/stdm#397]
When running through the Configuration Wizard with the inbuilt profiles on the Python 3 branch, an error is always raised during the final step:

   Identifier 'in_social_tenure_relationship_supporting_document_document_type_fkey' exceeds maximum length of 63 characters

I can't reproduce this using the same target database in fe7c37f, so it's likely being caused by a behavioural change in the Python 3 sqlalchemy version.

I'd appreciate some feedback on what might be the best approach to handle this error -- I think we'll need to revise the inbuilt models to shorten the "social_tenure_relationship_supporting_document_document_type" identifier, but will need some guidance on the best way to approach this given the current database structure.

**Comment by gkahiu** [comment]
I have forced sqlalchemy's `migrate` library to limit the name of foreign keys to a maximum of 63 characters in [8d22437](https://github.com/gltn/stdm/commit/8d22437a7e3bab2078e7654e023c525905ceb697). Let me know if this fixes the issue.

**Comment by nyalldawson** [comment]
I can confirm this is fixed now, thanks!
