### ISSUE TITLE
Git pull created an STDM sub-folder on the existing STDM parent folder

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#398]
When I did a git pull on my local master branch, the upstream master was created as a sub-folder on my local parent STDM folder. Is this the normal behavior with the new master branch?

**Comment by gkahiu** [comment]
Yes, this is in line with the best practices for QGIS plugin development so that dev (and other automation) scripts and files can be separated from the core plugin files, with the former not having to be incorporated in the plugin package.
