### ISSUE TITLE
System is unable to read/write settings from the registry 

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#402]
STDM is unable to read/write settings stored in the registry. Previous registry setting can be found under the following key:
_HKEY_CURRENT_USER\Software\QGIS\QGIS2\STDM_

**Comment by nyalldawson** [comment]
QGIS 3 no longer stores settings in the registry, and now always uses ini files within the user's QGIS profile. Have a look in the QGIS user profile under "QGIS/qgis3.ini" and you should see all the settings stored there.

You can directly open the profile folder by selecting "Settings" - "User Profiles" - "Open Active Profile Folder"
