### ISSUE TITLE
Wrong UI details for the Import module

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#404]
The first page of the Import module contains UI details that don't belong to the master branch. Currently, the master branch should have the following look on the first page:

![image](https://user-images.githubusercontent.com/155431/103456379-81566f00-4d06-11eb-9965-18392750632c.png)

**Comment by nyalldawson** [comment]
I'm confused here -- these changes were introduced by https://github.com/gltn/stdm/commit/319ed1d , and I can't see any commit since which reverted them.
