### ISSUE TITLE
Table View columns are not stretched

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#406]
Columns for table views on the Entity Browser windows are no longer stretched.

**Comment by nyalldawson** [comment]
Can you post some before/after screenshots please? I'm unable to reproduce any difference between master on QGIS 2 and the new QGIS 3 branch.

**Comment by jkariukidev** [comment]
> 
> 
> Columns for table views on the Entity Browser windows are no longer stretched.

Maybe this could help, resizing headers based on column counts. Refer here:

![image](https://user-images.githubusercontent.com/23359514/104152478-bf335180-53f0-11eb-8326-ef07917aa989.png)


[https://github.com/cb-flts/stdm/blob/5b26a1aacdb640ce8c84565e6d95fbc7fa73d3c6/ui/flts/certificate_upload/certificate_upload_widget.py#L84-L88](URL)
