### ISSUE TITLE
Stack trace when adding References table on STDM Data Table in the Document Designer

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#411]
I am getting the following stack trace when I try to add a _References_ table on the _Data Table_ on the Document Designer

`An error has occurred while executing Python code: 

NotImplementedError: QgsLayoutItemAttributeTable.getTableContents() is abstract and must be overridden 
NotImplementedError: QgsLayoutItemAttributeTable.getTableContents() is abstract and must be overridden`

**Comment by nyalldawson** [comment]
@pgathogo I've tracked this one down a bug in QGIS 3 itself. There's a fix here: https://github.com/qgis/QGIS/pull/40975 which I'll backport to both QGIS 3.16 and 3.10

**Comment by pgathogo** [comment]
Still getting the following stack trace when setting References tables

`An error has occurred while executing Python code: 

NotImplementedError: QgsLayoutItemAttributeTable.getTableContents() is abstract and must be overridden 
NotImplementedError: QgsLayoutItemAttributeTable.getTableContents() is abstract and must be overridden
`

**Comment by nyalldawson** [comment]
Because this is a bug in qgis itself we can't fix it in the plugin -- the only solution is to wait for the next round of qgis updates with the upstream fix.
