### ISSUE TITLE
OK button for the Feature Attributes Dialog remain disabled

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#418]
The OK button on the feature attributes dialog that appears after digitizing a raster layer remains disabled even after all attributes are entered.

**Comment by nyalldawson** [comment]
@pgathogo I can't reproduce this one -- can you please share a screencast or detailed steps to replicate?

**Comment by nyalldawson** [comment]
Reproducible using the Uganda Cuistomary Ownership profile
