### ISSUE TITLE
Stack Trace when you select View Social Tenure Relationship

### ISSUE THREAD

**Issue by pgathogo** [gltn/stdm#42]
The first time you run QGIS+STDM and before you setup the database (via the Database Wizard), when you click on "View Social Tenure Relationship" you get a stack trace, see attached image.

![initial_str](https://cloud.githubusercontent.com/assets/155431/11358065/c401d0f2-927f-11e5-961a-470dffacbb0f.png)

**Comment by gkahiu** [comment]
- The database has to be setup first prior to running the tool.

- This behaviour will be resolved in the config refactoring work scheduled
for release in v1.2

**Comment by eomwandho** [comment]
It might be a good idea to return a message to user like profile must be set up first.
