### ISSUE TITLE
Data Forms Wizard failed at the end when STDM installed via GLTN Plugin Repository

### ISSUE THREAD

**Issue by angkoraq** [gltn/stdm#43]
Hi STDM Team,

Reading the STDM User Manual 1.1, I learned and chose to try installing STDM through GLTN Plugin Repository with http://stdm.gltn.net/plugin/plugins.xml end point. The installation was successfully with both QGIS 2.8.7 and QGIS 2.14, and I found the STDM folder under the QGIS Python plugin folder. However, it always gave out a warning message in the QGIS Plugin Manager screen that: 
Installed version of this plugin is higher than any version found in repository
Author: Global Land Tool Network (GLTN)
Installed version: 1.1.2 (in C:\Users\xyz\.qgis2\python\plugins\stdm)
Available version: 1.1 (in GLTN Plugin Repository)

I've tried in vain many rounds of attempt to complete data form initial settings. When I got to the end of the process where you would click Finish to Update Existing STDM database or Show Generated SQL File. If I click on the latter, it shows an empty screen and the stdmConfig.sql is empty. If I persisted on clicking Finish to Update the database, it reports: (ProgrammingError) can't execute an empty query.

UPDATE: Eventually, I went back to install from the STDM Package/Bundle Installer x64 downloaded from NLTN STDM website. It still produced the same error. It didn't before. There must be some settings on my computer now that caused this. HOWEVER, If I chose the option Create a new STDM database, it succeeded but override my existing database unless I give it a new empty database.
Here is information about my environment: Windows 8.1 Pro, PostgreSQL 9.5, PostGIS 2.2.1.

I would be very appreciated if anyone could help shedding light on what I could overcome this.

Best regards,

Angkoraq

**Comment by gkahiu** [comment]
- The warning message in the canvas message bar is most likely caused by
   a previous existing version of the tool.
   - With regard to the error message, instead of selecting 'Update
   database' choose 'Create database' to create an initial schema of the
   database.

Let me know if this works.

We are also releasing a new version in a few weeks, this will simplify the
configuration setup. I t might be worthwhile to wait for this release.

Regards,

John

**Comment by angkoraq** [comment]
First of all, thanks a lot for your prompt response, John.

Yes, it works with the selection of Create a new STDM database. And I ended up installing QGIS 2.8.7 LTR and then through its Plugin Manager installing STDM in order to have a later version of QGIS. By the way, I did try the latest QGIS 2.14, but it doesn't work with Spatial Unit Manager of STDM.

Finally, I am looking forward to the latest and greatest STDM. I want to also take this opportunity to thank you and your team for creating and sharing this very promising GIS application. I am currently evaluating its technical capabilities for a conservancy team in Cambodia, and I see a great potential of utility and warranty of STDM.

Best regards,

Angkoraq

**Comment by gkahiu** [comment]
Glad to hear that it worked out for you.

Version 1.1 is tested on QGIS 2.8.x and some items might have changed in
QGIS 2.14. However, the new release will be compatible with QGIS versions
2.8 thru to 2.14. I will let you know once we release the beta version so
that you can also provide us with your valuable feedback.

If you need guidance on how to implement the tool for your program, please
do not hesitate to contact us.

Regards,

John
