### ISSUE TITLE
Error loading entity browser. Multiple select column not loading correctly due to missing lookup tables

### ISSUE THREAD

**Issue by SolomonN** [gltn/stdm#446]

**Comment by gkahiu** [comment]
I can confirm the issue, will look into it. 

Also, is this error related to issue #447? If so, we can merge it here.

**Comment by SolomonN** [comment]
Thanks John. The two are related.

**Comment by gkahiu** [comment]
I have pushed a fix, please test latest master and confirm the issue has been resolved.

**Comment by gkahiu** [comment]
Hi @SolomonN, kindly test and confirm that this has been fixed.
