### ISSUE TITLE
Error of Duplicate record while importing data

### ISSUE THREAD

**Issue by amanjhlp** [gltn/stdm#451]
Hi, while I import new data if there will be a duplicate record the attached error warning window will pop up.  to fix and enhance the issue in this case I suggest in the pop-up window the STDM will give me two options either don't import the duplicate records or replace them based on the unique columns such as : certificate code, reference code or Kobo submission id.

 Thank you,

![1](https://user-images.githubusercontent.com/81968735/113857575-59feba80-97ab-11eb-9bea-25886548fe7a.jpg)

**Comment by gkahiu** [comment]
Thanks @amanjhlp, are you running the latest beta version? I believe this issue has been addressed in the latest version, nonetheless @pgathogo will check.

**Comment by amanjhlp** [comment]
Yes I use the last version

**Comment by pgathogo** [comment]
This issue does not affect the master, however, it has been fixed on the specific branch that it occurs.
