### ISSUE TITLE
Error in configuration entity

### ISSUE THREAD

**Issue by daphneego** [gltn/stdm#452]
Hey everyone, 

I configured my structure wizard by adding new entities. However when I finish updating my wizard and try to open my structure entity the following error pops up> 
**Unable to load the entity in the browser. Check if the entity is configured correctly. Error: Could not reflect: requested table(s) not available in postgresql+psycopg2:**

Thanks for the help !!

**Comment by gkahiu** [comment]
Thanks for the feedback. Did the configuration wizard run successfully?

**Comment by daphneego** [comment]
Thanks for you response. Yes, no errors appeared

**Comment by gkahiu** [comment]
I cannot reproduce it but could you kindly send the configuration file? You can attach it to this chat.

**Comment by daphneego** [comment]
here it is. thanks for your help 
[configuration_update_08042021_11.57.log](https://github.com/gltn/stdm/files/6278445/configuration_update_08042021_11.57.log)

**Comment by gkahiu** [comment]
Can you send the file named _configuration.stc_ in the _.stdm_ folder?
