### ISSUE TITLE
Unable to edit a Social Ternure Relationship

### ISSUE THREAD

**Issue by juhudiduparc** [gltn/stdm#458]
I previously created an STR without supporting documents.
When I want to edit it by uploading a supporting document I am getting the error below
The error bellow is occurring on STDM 1.8. Same for STDM 1.7. 

![image](https://user-images.githubusercontent.com/21189476/131993100-5570ca6f-2261-424f-b71d-aae343e88dcc.png)

**Comment by pgathogo** [comment]
@juhudiduparc, this is well noted, I will investigate and revert.

**Comment by pgathogo** [comment]
This issue is fixed.

**Comment by juhudiduparc** [comment]
Thank you Paul
