### ISSUE TITLE
Dowloading Documents Feature - Fixed Importing Files With Arabic names

### ISSUE THREAD

**Issue by strabzounly** [gltn/stdm#489]
Fixed an issue related to Arabic filenames
when downloading files with Arabic names the downloading-documents feature raise up an error due to adding filename to log-file and saving filename to dataset "hl_supporting_docuemts"

![image](https://user-images.githubusercontent.com/16798654/183158192-22ab834a-241d-4738-a5de-b6166d9851ec.png)

**Comment by pgathogo** [comment]
Issue is fixed.
