### ISSUE TITLE
Accept License Every Time the Configuration Wizard is Loaded

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#49]
Each time the wizard is started, there is a request for choosing whether to accept license. Please make it once during first time configuration. Do not show this page on subsequent loads.

**Comment by pgathogo** [comment]
I guess "subsequent" load means loading happening on the current session, and not session started when a new instance of QGIS is fired

**Comment by gkahiu** [comment]
I mean first time when the plugin is used after installation. Subsequent
means even after QGIS has been closed or reloaded.

Regards,

John

**Comment by pgathogo** [comment]
Fixed, if  `StdmConfiguration.profiles` is empty license page is shown, else skips the page

**Comment by gkahiu** [comment]
I suggest you change the logic because we will be shipping the tool with a
default configuration so profiles will always return a value. Better you
use a flag that can be stored in the registry that can be applied on first
time loading of the plugin.

**Comment by pgathogo** [comment]
Fixed, added a registry key `ShowLicense` with 1 or 0 option to support this logic.
