### ISSUE TITLE
QGIS STDM Plug-in Installation Content Update

### ISSUE THREAD

**Issue by ostechman** [gltn/stdm#498]
Hi STDM Team,

The latest installation document (https://www.stdm.gltn.net/docs/1_8/Installing_STDM_1_8.pdf) mentions the second way of setup, which would be important for the non-Windows platforms, I would think. However, the latest STDM-1.8x release has not yet been  updated to the https://stdm.gltn.net/plugin/plugins.xml endpoint for such installation.

I would be much appreciated, if the team could complete that task as part of the latest and documented release to the public.
A couple of us in Cambodia would like to test out the latest program, while keeping an eye on its web application, too.

Last but not least, congratulations to the GLTN STDM team for putting out a new release and thanks very much indeed for this significant and meaningful contribution to the technical solutions of land administration!

Best regards,

Ostech Man

**Comment by gkahiu** [comment]
Greetings,

Many thanks for the feedback, this is appreciated.

> However, the latest STDM-1.8x release has not yet been updated to the https://stdm.gltn.net/plugin/plugins.xml endpoint for such installation.

We are currently working on this and it should be available in the plugin repository soon.

> A couple of us in Cambodia would like to test out the latest program, while keeping an eye on its web application, too.

We look forward to the feedback, please let us know if you require any guidance on its implementation. On the web application, this is currently on hold as we align the broader design of the tool to the emerging functional requirements as well as technological trends.

> Last but not least, congratulations to the GLTN STDM team for putting out a new release and thanks very much indeed for this significant and meaningful contribution to the technical solutions of land administration!

Thank you once again for this!

Best regards,

John
