### ISSUE TITLE
Tenure Types Not Loaded

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#50]
When loading the configuration from file, the tenure type lookups are not being loaded in the wizard.

**Comment by wondie** [comment]
In addition, when other lookups are created in addtion to tenure type, the whole lookup with the values  disappear when the wizard is loaded again.

**Comment by pgathogo** [comment]
@gkahiu are there default lookup values for the tenure type lookups? My current version creates an empty tenure type lookup.

**Comment by gkahiu** [comment]
Dear Paul,

There are no default types but the ones in the configuration file are not
being loaded.

Regards,

John

**Comment by pgathogo** [comment]
Hello John,

Am still investigating why the tenure types lookup values are not been loaded, and I've noticed when I reload the profiles from the StdmConfiguration instance the `tenure type lookup` has empty values`. Am suspecting the culprit might be in the ConfigurationFileSerializer class.

Regards
Paul

**Comment by gkahiu** [comment]
You are right Paul; there was an assumption in the configuration serializer
that this will be automatically referenced.

I will fix it and push ASAP.

Regards,

John

**Comment by pgathogo** [comment]
Thanks John.

Regards,

Paul
