### ISSUE TITLE
STDM500: Error during installation process.

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#500]
##  Expected Behavior
The installation process should go successfully without any errors.

##  Actual Behavior
At the end of the installation process, the following error is shown:
![image](https://github.com/gltn/stdm/assets/12920973/be764aff-0cfd-413e-a7be-5d0f4825ba97)

##  Steps to Reproduce the Problem
1. Double-click the STDM installer. 
2. Run through the installation process to the end.

**Comment by pgathogo** [comment]
Fixed in the latest installer.

**Comment by Thom03** [comment]
@pgathogo: There is a new error: 
![image](https://github.com/gltn/stdm/assets/12920973/accf756e-a306-4b9f-b790-856e4c8032b2)

**Comment by pgathogo** [comment]
@Thom03, this is well noted, however, since this error is not related to the earlier one on this thread, kindly create a new issue item for this one.
