### ISSUE TITLE
STDM501: Error trying to open help file(stdm.chm) file is missing

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#501]
##  Expected Behavior
The help file should open successfully after completing the installation.

##  Actual Behavior
When click help, the following error is thrown:
![image](https://github.com/gltn/stdm/assets/12920973/1d3b1d3a-48bb-455c-827e-e02228bd4b0f)

##  Steps to Reproduce the Problem
1. Open QGIS Lima for STDM. 
2. On the STDM Menu click Help button.

**Comment by pgathogo** [comment]
Fixed in the latest installer.
