### ISSUE TITLE
STDM502: STDM Tool not picking database port set during installation process.

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#502]
##  Expected Behavior
STDM should pick the default database port set during the installation process.

##  Actual Behavior
When open database properties, It picks default port for PostgreSQL which is 5432.
![image](https://github.com/gltn/stdm/assets/12920973/e8b171f2-bbab-4fef-b2d9-da0b767fe9a4)

##  Steps to Reproduce the Problem
1. Open QGIS Lima for STDM. 
2. Open options windows, click on database properties 
3. Confirm the port set on Database conform with the one set during installation.

## Additional details:
- The port was changed during installation to 5436.

**Comment by pgathogo** [comment]
Fixed in the latest installer.
