### ISSUE TITLE
STDM508 Search button on the Search windows give an error on Entity Module

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#504]
##  Expected Behavior
The search button is to work well on the Entity module.

##  Actual Behavior
Search button should give results.

##  Steps to Reproduce the Problem
1. Open QGIS  for STDM. 
2. Login into STDM
3. Open Entity Windows,
4. Click the search button
5. Key in the  parameters for search and click the search button

## Additional details:
![image](https://github.com/gltn/stdm/assets/12920973/a0dfd66a-372c-4900-92f4-99d72114dd44)

**Comment by pgathogo** [comment]
This is issues is fixed.
