### ISSUE TITLE
STDM509: Reset button on the search window gives an error when clicked

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#505]
##  Expected Behavior
The reset button on the search window should reset search values.

##  Actual Behavior
The reset button on the search window gives an error when clicked.

##  Steps to Reproduce the Problem
1. Open QGIS  for STDM. 
2. Login into STDM
3. Open Entity Windows,
4. Click the search button
5. Key in the  parameters for search and click the reset button

## Additional details:
![image](https://github.com/gltn/stdm/assets/12920973/3d229d94-be40-49bf-8357-ab8c18694908)

**Comment by pgathogo** [comment]
This issue is fixed.
