### ISSUE TITLE
STDM510: Tool capturing future Dates where not applicable

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#506]
##  Expected Behavior
The tool should prevent users from capturing future dates that are not applicable.

##  Actual Behavior
The tools allow users to capture future dates where they are not applicable.

##  Steps to Reproduce the Problem
1. Open QGIS  for STDM. 
2. Login into STDM
3. Open Entity Windows,
4. Try to key in date data for one entity with a date field.

## Additional details:
![image](https://github.com/gltn/stdm/assets/12920973/bfb67b91-f685-44cc-8d36-ec161bf679ea)

**Comment by pgathogo** [comment]
@Thom03 - For date data types, you can add the constraints when you are creating the column in the Configuration Wizard. You can set the Minimum and Maximum date constraint on your column:
![image](https://github.com/gltn/stdm/assets/155431/195788c7-a19e-42cc-bf8a-5aea7839baef)

And when you are entering the data, the date widget will be constrained by your settings:

![image](https://github.com/gltn/stdm/assets/155431/4be4e648-d2bc-411f-94f9-a3328def12cd)
