### ISSUE TITLE
STDM511: Python Error of sync_in_place _button_state  as a continue to operate the tool

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#507]
##  Expected Behavior
When operating the tool, it should not get a Python error

##  Actual Behavior
After some time, the tool gives me a Python error, as shown in the screenshot above.

##  Steps to Reproduce the Problem
1. Open QGIS  for STDM. 
2. Login into STDM
3. Continue with normal operations.

## Additional details:
![image](https://github.com/gltn/stdm/assets/12920973/b4697c64-cd96-4447-a6f2-d887462e8f38)

**Comment by Thom03** [comment]
Sure, @pgathogo, he can confirm. It keeps coming if I run into an error. I have to restart the QGIS for it to disappear completely.

**Comment by pgathogo** [comment]
Yes, this issue is related to the Processing plugin.
