### ISSUE TITLE
STDM513: Retrieving information on Geom Location Field.

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#509]
##  Expected Behavior
Retrieve geom data.

##  Actual Behavior
Retrieving information on Geom Location Field.

##  Steps to Reproduce the Problem
1. Open QGIS  for STDM. 
2. Login into STDM.
3. Open STR Window.
4. Click on the Spatial Unit Tab.

## Additional details:
![image](https://github.com/gltn/stdm/assets/12920973/ed3891d8-4f03-4b03-88a9-e1e4ba094eaa)

- User may think the geom information is missing.

**Comment by pgathogo** [comment]
Since we don't use the geometry data in this module, we shall find a way of hiding the column.

**Comment by Thom03** [comment]
@pgathogo, that also works.

**Comment by pgathogo** [comment]
This issue has been fixed.
