### ISSUE TITLE
STDM517: Error creating a new data profile.

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#514]
##  Expected Behavior
Creating a new data profile. After editing entities and attributes.

##  Actual Behavior
Error creating a new data profile after editing entities and attributes. System throwing error on OrderDict mutated during iteration.

##  Steps to Reproduce the Problem
1. Open QGIS  for STDM. 
2. Login into STDM
3. Open Configuration Wizard
4. Create a new profile with all the entities and attributes.
5. Go to the last STR step, and then go back to edit the entities and attributes.
6. Click Save.

## Additional details:
![image](https://github.com/user-attachments/assets/23904d93-529c-43d6-a5ed-73e05f55f5ad)

**Comment by pgathogo** [comment]
@Thom03 Step 5 is not very clear, please elaborate more (maybe screenshots would help)

Unable to reproduce the issue.
