### ISSUE TITLE
STDM519: Error in restoring a Backed-up configuration 

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#516]
##  Behavior
The application throws an error that the configuration backup can not be restored because the system has detected that the PostGIS extension is missing. The error persists even if you try to change to a different database unless you restart the application.

##  Steps to Reproduce the Problem
1. Open QGIS  for STDM. 
2. Login into STDM.
3. Under Configuration Wizard.
4. Click Configuration Management.
5. From the Menu, Click Restore.

## Additional details:
![image](https://github.com/user-attachments/assets/18b03a5a-06cb-47a9-865b-4b066a9716ab)

**Comment by pgathogo** [comment]
Make sure you have installed the PostGIS extension in the instance of the database server you are running.
