### ISSUE TITLE
STDM520: Error when try to add null records on entities. 

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#517]
##  Behavior
The application should notify users when entering null records on entities that violate the configuration. Instead, it throws a Python error instead of a user-friendly message. See on the screenshot on Additional details.

##  Steps to Reproduce the Problem
1. Open QGIS  for STDM. 
2. Login into STDM.
3. Under Entities.
4. Click One Entities.
5. From the Menu, Try to enter records.

## Additional details:
![image](https://github.com/user-attachments/assets/ba1553ab-91d1-4d07-b77d-c709bbf4108d)

**Comment by pgathogo** [comment]
@Thom03 This is noted. The checks for mandatory columns on the entity data forms seem to be broken.

**Comment by pgathogo** [comment]
This issue has been fixed.
