### ISSUE TITLE
STDM521: Error when exporing data as shapefile, CSV, Mapinfo, GPX and DFX.

### ISSUE THREAD

**Issue by Thom03** [gltn/stdm#518]
##  Behavior
When exporting STDM data as shapefile, CSV, MapInfo, GPX, or DFX, the application throws an error. The application keeps throwing an error of driver to available for every format. For more details, refer to the screenshot in the additional section.

##  Steps to Reproduce the Problem
1. Open QGIS  for STDM. 
2. Login into STDM.
3. Click Export Data.
5. Select the Format and define the destination file.

## Additional details:
![image](https://github.com/user-attachments/assets/259bd683-1097-4f08-bd18-344d68ffab27)

**Comment by pgathogo** [comment]
Unable to reproduce this issue.

**Comment by Thom03** [comment]
@pgathogo , I demonstrated this during our issue onboarding meeting. Kindly let's discuss this in detail to close. Thanks

**Comment by pgathogo** [comment]
Unable to reproduce this issue in multiple environments. @Thom03 please check your setup.
