### ISSUE TITLE
Incorporate Profile Description

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#53]
I have added a description attribute in the Profile class, please update in the wizard accordingly.

**Comment by pgathogo** [comment]
Done. Profile description now showing on the wizard.

**Comment by gkahiu** [comment]
Thanks Paul. Please put a 'Description:' label so that the user can actually see that the text appearing below the combobox refers to the profile description.

**Comment by pgathogo** [comment]
Fixed, added a description label.
