### ISSUE TITLE
social_tenure_relationship_supporting_document column has profile prefix

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#57]
The **social_tenure_relationship_supporting_document** table's column called **...supporting_doc_id** is created with a profile prefix at the being of its name. This makes it hard to access the column dynamically as sqlachemy column name needs to be written as a property.

**Comment by gkahiu** [comment]
The following code snippet should enable you to access the column object:
`p = current_profile()`
`social_tenure = p.social_tenure`
`social_tenure_supporting_docs = social_tenure.supporting_doc`
`supporting_doc_id_col = social_tenure_supporting_docs.document_reference`

Please note that `supporting_doc_id_col` is a column object of type `ForeignKeyColumn`, see its implementation [here](https://github.com/gltn/stdm/blob/ref_config_mod/data/configuration/columns.py#L502).

**Comment by wondie** [comment]
Thank you for the help. However, my problem was not on accessing the column object. The problem is on the database, the column has the prefix of the profile. For instance, if my profile is wondie, the column name is wo_supporting_doc_id which makes it hard to access the column object. The problem area is [here](https://github.com/gltn/stdm/blob/8cd930177312f21b46f724fbcc2921e180b70407/ui/new_str_wiz.py#L342).

**Comment by gkahiu** [comment]
Use Python's `setattr` built-in function:
`setattr(STR_relation, '[column_name]', model_obj.id)`

However, there is a more standardized way of saving the documents and relationships with the new configuration.

**Comment by wondie** [comment]
Thank you! I will modify it as you have suggested.

**Comment by wondie** [comment]
Unfortunately, I have to now use `model_obj.saveMany() `method and for that, I have to collect then in a for loop. The added suffix inside the column is making hard for me to use  SaveMany. This is because, I use the following.

```
            str_supp_doc_model = entity_model(
                self.curr_profile.social_tenure.supporting_doc,
                True
            )
            str_supp_doc_model_obj = str_supp_doc_model()
            str_doc_obj = OrderedDict()
            ...
                .....
                            for doc_obj in model_obj:
                                str_doc_objs = str_supp_doc_model(
                                    social_tenure_relationship_id = obj.id
                                )
                                setattr(
                                    str_supp_doc_model_obj,
                                    self.prefix + '_supporting_doc_id',
                                    doc_obj.id
                                )
                                str_doc_obj[str_doc_objs] = str_doc_objs

                                doc_obj.save()
                            str_supp_doc_model_obj.saveMany(str_doc_obj.values())
```
I have to now add it inside str_doc_objs OrderedDic instead of using setattr as setattr doesn't save the supporting_doc_id any longer under saveMany. So I want to put it inside str_doc_objs as shown below. 
```

                               str_doc_objs = str_supp_doc_model(
                                    social_tenure_relationship_id = obj.id, 
                                    supporting_doc_id = doc_obj.id
                                )
```
Unfortunately, supporting_doc_id column has prefix which make it impossible to use it in this way. So is it possible to remove the prefix or is there any other good method of saveMany?

**Comment by wondie** [comment]
This issue is fixed!
