### ISSUE TITLE
Load Configuration Error message not properly formatted

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#59]
Load Configuration Error message is not properly formatted. The 'u' is seen at the beginning of the message and new line '\n' is seen. 

![image](https://cloud.githubusercontent.com/assets/9709624/15258106/5d11b362-1952-11e6-9abe-109c50b4d63c.png)

**Comment by gkahiu** [comment]
Fixed.

**Comment by wondie** [comment]
Great!
