### ISSUE TITLE
Value_list class and tenure_type_collection property doesn't have id for the values

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#61]
Value_list class and tenure_type_collection property doesn't have id for the values. This is needed to convert lookup ids to values for display. 

Edit: I realized that the configuration can't know the id unless it keeps track of first entry and removals and calculate id. So should I just use the model to convert lookup ids to values?

**Comment by gkahiu** [comment]
Can you search by code or by value?

**Comment by wondie** [comment]
Value_list class and tenure_type_collection, only have code and value. When information loads from the database, it picks the id as only the id is stored when used in child tables. Now that id needs to be converted to value for display. How to achieve that in less expensive way is my question.

**Comment by gkahiu** [comment]
Did the `entity_model` function assist in getting the lookup value?

**Comment by wondie** [comment]
Yes definitely! I then used getattr method as you have suggested.
