### ISSUE TITLE
When adding a lookup column, all lookup values plus the selected lookup values loads

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#62]
When adding a lookup column, all lookup values plus the selected lookup values loads in the values box. 
Please see the image below. 
![image](https://cloud.githubusercontent.com/assets/9709624/15304210/b1b9bd82-1bc4-11e6-9af4-52345eb12a6d.png)

**Comment by gkahiu** [comment]
Wondie,

Please test if the latest commit resolved this issue?

Thanks.

**Comment by wondie** [comment]
Hi John, 

I have tested the issue and it is now fixed!

Regards,
Wondimagegn

**Comment by gkahiu** [comment]
Good stuff, thanks!

**Comment by wondie** [comment]
Unfortunately, this issue is back. 
![image](https://cloud.githubusercontent.com/assets/9709624/15530498/5d43816c-225d-11e6-942f-87141a2de45d.png)
