### ISSUE TITLE
Confirmation Before Deleting Profile

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#64]
It will be good to put a confirmation message box prior to deleting the profile.

**Comment by pgathogo** [comment]
Confirmation box added.

**Comment by gkahiu** [comment]
Great. Can you also put in the message box the child entities that will be affected by the deletion; you can get the children entities by using the children function of the entity to be deleted i.e.

`children_entities = delete_entity.children()`

This will warn users that the related children tables will also be deleted.
