### ISSUE TITLE
configuration.stc does not exist. Configuration file cannot be loaded

### ISSUE THREAD

**Issue by geonomad-consulting** [gltn/stdm#66]
When a (Linux/Mac OSX) user install stdm plugin directly from the repo, this particular files is not available, could there be a remedy?

**Comment by gkahiu** [comment]
There will be a default one that will be shipped with the system. In the
meantime, you can use the attached one.

**Comment by geonomad-consulting** [comment]
I will create a sample and put it inside the template folder

**Comment by gkahiu** [comment]
A default configuration package will be shipped with plugin.
