### ISSUE TITLE
Save Configuration Update Status to File

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#71]
It will be good if the messages produced during the schema update process can be saved; this will be particularly useful if users can share these files in case of any warnings or errors during the update process for troubleshooting purposes.

Could you incorporate a save option in the last page and activate it after the process has completed (whether successfully or not)?

**Comment by pgathogo** [comment]
Enhancement added. Update information shown when updating the database is now saved in a file (`update_info.log`) under the folder `.stdm`

**Comment by gkahiu** [comment]
Thanks Paul. Can you also append the date and time to the file name?
