### ISSUE TITLE
Some texts are partly hidden from Configuration Wizard dialogs. 

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#72]
Please see the image below. 
![image](https://cloud.githubusercontent.com/assets/9709624/15521086/856ecbc4-2212-11e6-9c43-9e3c5104f409.png)

![image](https://cloud.githubusercontent.com/assets/9709624/15521099/90fc2cc0-2212-11e6-9714-9fd77bb606f6.png)

![image](https://cloud.githubusercontent.com/assets/9709624/15521140/d0131c02-2212-11e6-93fb-9b6889316193.png)

Edit:
![image](https://cloud.githubusercontent.com/assets/9709624/15530167/75724504-225b-11e6-95c8-5b0a1d331a44.png)

**Comment by gkahiu** [comment]
@pgathogo, are you using layout in these dialogs?

**Comment by pgathogo** [comment]
@gkahiu , the profile dialog was missing a layout, I've fixed that, but all the rest have layouts. Are you experiencing the same behavior on your dialogs?

**Comment by gkahiu** [comment]
The following have no layouts:

   1. Profile editor (as already mentioned).
   2. All list views/widgets and table views/widgets in the* Entity
   Customization* page of the wizard (3rd page).
   3. Datetime column editor.
   4. Geometry column editor.
   5. Not sure about the *Defining Social Tenure Tables* page. Please
   confirm.

Regards,

John

**Comment by pgathogo** [comment]
Fixed. Added layouts in all affected pages.
