### ISSUE TITLE
When adding a lookup as a column of an entity, all lookup values are listed and the first one twice

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#73]
When I added a lookup as a column of an entity while selecting the same lookup. The values of the lookup has loaded again on top of the existing ones. 
![image](https://cloud.githubusercontent.com/assets/9709624/15521333/e1e980f0-2213-11e6-8eff-7ecb1e6eb32b.png)

Edit:
I addition, I got a similar issue. In this case, when I created a column using lookup, all lookup values are listed with a repetition of values of the first lookup.  
![image](https://cloud.githubusercontent.com/assets/9709624/15530498/5d43816c-225d-11e6-942f-87141a2de45d.png)

**Comment by pgathogo** [comment]
Fixed.

**Comment by wondie** [comment]
I have confirmed that it is fixed!
