### ISSUE TITLE
Most column settings are disabled in the configuration wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#74]
Most column settings are disabled in the configuration wizard. If are going to be enabled in the future, well and good. The one I noticed is, date type can not be searchable. We can use searchable for date type to search by date of birth. 

Character varying cannot be mandatory. For instance spatial_unit code is character varying but it should be unique.

**Comment by gkahiu** [comment]
I believe it depends on the data type but character varying should be fully flexible as specified by the user but there are options that should be disabled by default.

@pgathogo I remember we talked about this some time back, could you prepare a simple table showing column configurations based on types; we can use this to discuss further. Should be something simple like:

Data Type | Default Checked Options | Disabled Options
-----------------------------------------------------------------------
Character varying | -Searchable | None
Geometry | - Indexed | Not searchable
etc.

**Comment by wondie** [comment]
That would be great.

**Comment by pgathogo** [comment]
@gkahiu , @wondie,  I have created a simple table with default state of column data types, I've shared a link to this document kindly confirm and give your comments.

**Comment by wondie** [comment]
In my view, none of them needs to be disabled. Because, we never know if they user want them to be mandatory, indexed, unique and searchable. For instance, Varying-length text can be set to be unique for spatial unit code. Date can be set to be mandatory for age, so that age must be filled. We can leave all of them unchecked but enabled except the Varying-length text, which is searchable by default.

**Comment by wondie** [comment]
@pgathogo and @gkahiu , now the column settings enabled appropriately. However, I have one issue. For Unlimited Length text all settings are disabled. In my view, some should be enabled. 
1. Mandatory - might be needed by the user. So it is good to enable it. 
2. Searchable - can be searchable also but with keyword search. If that is not possible now, it is good to disable it. 
The rest are ok.

**Comment by wondie** [comment]
I see that the whole number column settings are enabled. I think the only thing remaining is to disable indexed.

**Comment by wondie** [comment]
This issue is fixed!
