### ISSUE TITLE
Renaming an entity, didn't remove the renamed one and shows a python error

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#77]
The issue happens when I renamed an entity to something else. Both the old and the new names stayed in the entity box and on the entity and next page as shown below. 

![image](https://cloud.githubusercontent.com/assets/9709624/15530618/2e1d2c52-225e-11e6-8f8d-fddcc421b3d3.png)
spatial unit (old name), person (new name)

Then when I clicked on the renamed one, the following python error is shown. 

An error has occurred while executing Python code:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\ui\wizard\wizard.py", line 779, in entity_changed
    columns = view_model.entity_byId(row_id).columns.values()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\ui\wizard\custom_item_model.py", line 53, in entity_byId
    return self._entities.values()[id]
IndexError: list index out of range

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.3-Wien Wien, exported

Python path: ['C:/Users/Wondim/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python', u'C:/Users/Wondim/.qgis2/python', u'C:/Users/Wondim/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\python_dateutil-2.1-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Wondim/.qgis2//python', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party\\fontTools']

**Comment by gkahiu** [comment]
@pgathogo, renaming entities should not be enabled due to PostgreSQL 'limitations'.

**Comment by wondie** [comment]
What about allowing renaming during profile creation but disable editing, once the database is created? I think that will give more flexibility.

**Comment by wondie** [comment]
Now when I renamed an entity and clicked finish, I get the following error inside the wizards last page box. 

```
Configuration update started ...
Scanning for changes in turkana profile...
Removing redundant foreign key constraints...
Error in removing fk_tu_special_id_tu_social_tenure_relationship_party_id foreign key constraint.
fk_tu_check_gender_id_tu_party_gender foreign key constraint successfully removed.
fk_admin_spatial_unit_set_id_tu_party_admin_spatial_unit foreign key constraint successfully removed.
fk_tu_spatial_unit_id_tu_spatial_unit_supporting_document_Spatial unit_id foreign key constraint successfully removed.
Error in removing fk_tu_spatial_units_id_tu_social_tenure_relationship_spatial_unit_id foreign key constraint.
Deleting Party entity...
(InternalError) cannot drop table tu_party because other objects depend on it
DETAIL:  constraint tu_social_tenure_relationship_party_id_fkey on table tu_social_tenure_relationship depends on table tu_party
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
 '\nDROP TABLE tu_party' {}
Failed to update configuration. Check error logs.
```

**Comment by pgathogo** [comment]
Fixed,  disabled editing entities that exist in the database.

**Comment by wondie** [comment]
I have confirmed that this issue is fixed!
