### ISSUE TITLE
Failure to create profile when using admin_spatial_unit_set

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#79]
When creating a profile with admin_spatial_unit_set as one of the columns data type, I got the following error. The error below is related to admin_spatial_unit_set.
![image](https://cloud.githubusercontent.com/assets/9709624/15531241/f46d40c4-2261-11e6-9239-90656b2efa88.png)

When I removed admin_spatial_unit_set column, the profile is created successfully. 

Edit:
I just found out that, the column admin_spatial_unit_set is created but it is not foreign key column. 
Below is the full table creation query. 

CREATE TABLE tu_party
(
  id serial NOT NULL,
  name character varying(30),
  gender integer,
  admin_spatial_unit integer,
  CONSTRAINT tu_party_pkey PRIMARY KEY (id),
  CONSTRAINT tu_party_gender_fkey FOREIGN KEY (gender)
      REFERENCES tu_check_gender (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);

**Comment by gkahiu** [comment]
Fixed in commit [897e43f](https://github.com/gltn/stdm/commit/897e43fb0025b4aa6e9bf957215b5fdf869d2838).

**Comment by wondie** [comment]
I have confirmed that it is working now!
