### ISSUE TITLE
Selection of Default Profile Upon Login

### ISSUE THREAD

**Issue by gkahiu** [gltn/stdm#82]
@wondie, thanks for incorporating the default profile check upon login. However, I have come across a couple of issues:
1. The message box is shown before the tools  in the toolbar have loaded. The desired scenario is to show the messagebox after all the tools have loaded in the toolbar.
2. The title of the message box is 'Default Profile Error' and yet the icon in the message box shows a question mark so I suggest you either change the message box type to depict a warning or change the title.
3. When I choose 'No', the error shown below appears:

![default profile2](https://cloud.githubusercontent.com/assets/3840267/15542120/108d7e28-2298-11e6-942c-65b6efa80e61.PNG)
 
The culprit is `self.spatial_unit = self._curr_profile.social_tenure.spatial_unit`, I will fix it (issue no.3 above) and commit.

**Comment by wondie** [comment]
Thank you for finding the issue. I will fix it.
