### ISSUE TITLE
Editing entity results in the disappearance from the entities box

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#83]
When I edited spatial unit, just by unchecking allow supporting document, spatial unit disappears from the box as shown in the image below. 
![image](https://cloud.githubusercontent.com/assets/9709624/15566057/7ab329da-2327-11e6-90cc-7dd72200c1c0.png)

**Comment by pgathogo** [comment]
Fixed.

**Comment by wondie** [comment]
I have confirmed that it is fixed!
