### ISSUE TITLE
Reloading all STDM Modules after configuration wizard Finish button clicked

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#84]
A the wizard creates database tables and add columns, for the changes to be seen, some modules needs to be restarted. To prevent user re-login, the modules can be restarted by running loadModules() located in plugin.py. It would be great to integrate this feature with the configuration wizard finish button.

**Comment by wondie** [comment]
This issue is fixed by [this commit](https://github.com/gltn/stdm/commit/a9597d1fd072eee045555e4533185d0c0ebcfd24).

**Comment by gkahiu** [comment]
Excellent, will test and revert.
