### ISSUE TITLE
Adding the ability to disable supporting document for a STR in Configuration Wizard

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#88]
The configuration's `current_profile().social_tenure.supporting_document` returns a Boolean, showing if supporting document is enabled for the current profile's social tenure relationship. Even though the wizard has option to enable supporting document for an entity, there is no option to enable or disable supporting document for STR. It would be great to include this feature.

**Comment by pgathogo** [comment]
This is not optional, its a requirement for the STDM model.

**Comment by wondie** [comment]
That is good! I will make it optional in new STR Wizard.
