### ISSUE TITLE
Configuration Wizard Error:  update or delete on table "check_social_tenure_relationship_document_type

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#94]
I got the following error when running the wizard and clicked Finish. 
![image](https://cloud.githubusercontent.com/assets/9709624/15991327/842b02be-30b8-11e6-8a20-de19932c834a.png)

I have attached the database [here](https://www.dropbox.com/s/bc4row9ealwkr3a/stdm.backup?dl=0).

**Comment by gkahiu** [comment]
Seems like an error when deleting from a table already containing data. Am
out in the field so will not have much time this week to look at it, will
revert next week.

**Comment by wondie** [comment]
That is noted.

**Comment by wondie** [comment]
This issue is no longer there. I didn't recreate the database.
