### ISSUE TITLE
The configuration Wizard is not reading a newly added document type after a QGIS restart

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#95]
I have two document types, General and Title for tu_check_social_tenure_relationship_document_type as shown in the image. In addition, they are also shown in configuration.stc. However, after a QGIS restart, the configuration is only showing the default one (General). 

![image](https://cloud.githubusercontent.com/assets/9709624/15998365/71afa3ea-3146-11e6-98fb-6205a5e63417.png)

![image](https://cloud.githubusercontent.com/assets/9709624/15998379/7ed702de-3146-11e6-8f0d-94f040e62d87.png)

**Comment by pgathogo** [comment]
This bug has been fixed. 

To fix it I had to make a few changes to the following files;

`profile.py`- added a boolean parameter `is_new` in the `Profile` class constructor which is set to True by default. The parameter get passed to method `_create_social_tenure`, which subsequently sets the default parameter `supports_documents` of the same method.

`config_serializer.py` - Inside the method `read_xml`, when instantiating `Profile` I pass the parameter `is_new = False`. This will prohibit the creation of `EntitySupportingDocument` IF the profile is been read from the configuration file.

**Comment by wondie** [comment]
This is great Paul! I have confirmed that the issue is fixed!

**Comment by gkahiu** [comment]
Hi Paul,

Thanks for making these changes. However, it brought about another issue in
that the supporting documents object for social tenure relationships for
existing profiles was returning None. However, we fixed it with Wondie in
the config serializer and value list modules and rolled back the changes
you made. All sorted out now.

Regards,

John
