### ISSUE TITLE
No multi-selection capability on entity browser select mode

### ISSUE THREAD

**Issue by wondie** [gltn/stdm#98]
I tried to multi-select in entity browser select mode but it only allows one. I know this might lead to some changes but it would be great to include it especially as it compliments New STR wizard multi party.

**Comment by gkahiu** [comment]
Please check out the latest release and confirm that multiple select is enabled in the entity browser.

**Comment by wondie** [comment]
I just checked but it is not enabled.

**Comment by wondie** [comment]
I tried with the Control Key but when I tried the Shift Key it still work still. As you know, in Windows and MS Office, multi-selection is one by one is done using the Control Key. The shift key is used to select items between two selections. Could you make it similar to Windows if possible?

**Comment by wondie** [comment]
The multi-selection works now! I have also tested it on new STR wizard and it works.

**Comment by wondie** [comment]
It also works well with Document Generator.
